// Code generated by ent, DO NOT EDIT.

package enterprise

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldName, v))
}

// ShortName applies equality check predicate on the "short_name" field. It's identical to ShortNameEQ.
func ShortName(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldShortName, v))
}

// CreditCode applies equality check predicate on the "credit_code" field. It's identical to CreditCodeEQ.
func CreditCode(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldCreditCode, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldAddress, v))
}

// Scale applies equality check predicate on the "scale" field. It's identical to ScaleEQ.
func Scale(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldScale, v))
}

// Industry applies equality check predicate on the "industry" field. It's identical to IndustryEQ.
func Industry(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldIndustry, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldParentID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldStatus, v))
}

// ContactName applies equality check predicate on the "contact_name" field. It's identical to ContactNameEQ.
func ContactName(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldContactName, v))
}

// ContactPhone applies equality check predicate on the "contact_phone" field. It's identical to ContactPhoneEQ.
func ContactPhone(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldContactPhone, v))
}

// ContactEmail applies equality check predicate on the "contact_email" field. It's identical to ContactEmailEQ.
func ContactEmail(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldContactEmail, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldNotes, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldBalance, v))
}

// TotalRecharged applies equality check predicate on the "total_recharged" field. It's identical to TotalRechargedEQ.
func TotalRecharged(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldTotalRecharged, v))
}

// AdminUserID applies equality check predicate on the "admin_user_id" field. It's identical to AdminUserIDEQ.
func AdminUserID(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldAdminUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldName, v))
}

// ShortNameEQ applies the EQ predicate on the "short_name" field.
func ShortNameEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldShortName, v))
}

// ShortNameNEQ applies the NEQ predicate on the "short_name" field.
func ShortNameNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldShortName, v))
}

// ShortNameIn applies the In predicate on the "short_name" field.
func ShortNameIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldShortName, vs...))
}

// ShortNameNotIn applies the NotIn predicate on the "short_name" field.
func ShortNameNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldShortName, vs...))
}

// ShortNameGT applies the GT predicate on the "short_name" field.
func ShortNameGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldShortName, v))
}

// ShortNameGTE applies the GTE predicate on the "short_name" field.
func ShortNameGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldShortName, v))
}

// ShortNameLT applies the LT predicate on the "short_name" field.
func ShortNameLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldShortName, v))
}

// ShortNameLTE applies the LTE predicate on the "short_name" field.
func ShortNameLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldShortName, v))
}

// ShortNameContains applies the Contains predicate on the "short_name" field.
func ShortNameContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldShortName, v))
}

// ShortNameHasPrefix applies the HasPrefix predicate on the "short_name" field.
func ShortNameHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldShortName, v))
}

// ShortNameHasSuffix applies the HasSuffix predicate on the "short_name" field.
func ShortNameHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldShortName, v))
}

// ShortNameEqualFold applies the EqualFold predicate on the "short_name" field.
func ShortNameEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldShortName, v))
}

// ShortNameContainsFold applies the ContainsFold predicate on the "short_name" field.
func ShortNameContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldShortName, v))
}

// CreditCodeEQ applies the EQ predicate on the "credit_code" field.
func CreditCodeEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldCreditCode, v))
}

// CreditCodeNEQ applies the NEQ predicate on the "credit_code" field.
func CreditCodeNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldCreditCode, v))
}

// CreditCodeIn applies the In predicate on the "credit_code" field.
func CreditCodeIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldCreditCode, vs...))
}

// CreditCodeNotIn applies the NotIn predicate on the "credit_code" field.
func CreditCodeNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldCreditCode, vs...))
}

// CreditCodeGT applies the GT predicate on the "credit_code" field.
func CreditCodeGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldCreditCode, v))
}

// CreditCodeGTE applies the GTE predicate on the "credit_code" field.
func CreditCodeGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldCreditCode, v))
}

// CreditCodeLT applies the LT predicate on the "credit_code" field.
func CreditCodeLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldCreditCode, v))
}

// CreditCodeLTE applies the LTE predicate on the "credit_code" field.
func CreditCodeLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldCreditCode, v))
}

// CreditCodeContains applies the Contains predicate on the "credit_code" field.
func CreditCodeContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldCreditCode, v))
}

// CreditCodeHasPrefix applies the HasPrefix predicate on the "credit_code" field.
func CreditCodeHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldCreditCode, v))
}

// CreditCodeHasSuffix applies the HasSuffix predicate on the "credit_code" field.
func CreditCodeHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldCreditCode, v))
}

// CreditCodeEqualFold applies the EqualFold predicate on the "credit_code" field.
func CreditCodeEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldCreditCode, v))
}

// CreditCodeContainsFold applies the ContainsFold predicate on the "credit_code" field.
func CreditCodeContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldCreditCode, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldAddress, v))
}

// ScaleEQ applies the EQ predicate on the "scale" field.
func ScaleEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldScale, v))
}

// ScaleNEQ applies the NEQ predicate on the "scale" field.
func ScaleNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldScale, v))
}

// ScaleIn applies the In predicate on the "scale" field.
func ScaleIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldScale, vs...))
}

// ScaleNotIn applies the NotIn predicate on the "scale" field.
func ScaleNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldScale, vs...))
}

// ScaleGT applies the GT predicate on the "scale" field.
func ScaleGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldScale, v))
}

// ScaleGTE applies the GTE predicate on the "scale" field.
func ScaleGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldScale, v))
}

// ScaleLT applies the LT predicate on the "scale" field.
func ScaleLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldScale, v))
}

// ScaleLTE applies the LTE predicate on the "scale" field.
func ScaleLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldScale, v))
}

// ScaleContains applies the Contains predicate on the "scale" field.
func ScaleContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldScale, v))
}

// ScaleHasPrefix applies the HasPrefix predicate on the "scale" field.
func ScaleHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldScale, v))
}

// ScaleHasSuffix applies the HasSuffix predicate on the "scale" field.
func ScaleHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldScale, v))
}

// ScaleEqualFold applies the EqualFold predicate on the "scale" field.
func ScaleEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldScale, v))
}

// ScaleContainsFold applies the ContainsFold predicate on the "scale" field.
func ScaleContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldScale, v))
}

// IndustryEQ applies the EQ predicate on the "industry" field.
func IndustryEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldIndustry, v))
}

// IndustryNEQ applies the NEQ predicate on the "industry" field.
func IndustryNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldIndustry, v))
}

// IndustryIn applies the In predicate on the "industry" field.
func IndustryIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldIndustry, vs...))
}

// IndustryNotIn applies the NotIn predicate on the "industry" field.
func IndustryNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldIndustry, vs...))
}

// IndustryGT applies the GT predicate on the "industry" field.
func IndustryGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldIndustry, v))
}

// IndustryGTE applies the GTE predicate on the "industry" field.
func IndustryGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldIndustry, v))
}

// IndustryLT applies the LT predicate on the "industry" field.
func IndustryLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldIndustry, v))
}

// IndustryLTE applies the LTE predicate on the "industry" field.
func IndustryLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldIndustry, v))
}

// IndustryContains applies the Contains predicate on the "industry" field.
func IndustryContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldIndustry, v))
}

// IndustryHasPrefix applies the HasPrefix predicate on the "industry" field.
func IndustryHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldIndustry, v))
}

// IndustryHasSuffix applies the HasSuffix predicate on the "industry" field.
func IndustryHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldIndustry, v))
}

// IndustryEqualFold applies the EqualFold predicate on the "industry" field.
func IndustryEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldIndustry, v))
}

// IndustryContainsFold applies the ContainsFold predicate on the "industry" field.
func IndustryContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldIndustry, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldParentID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldStatus, v))
}

// ContactNameEQ applies the EQ predicate on the "contact_name" field.
func ContactNameEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldContactName, v))
}

// ContactNameNEQ applies the NEQ predicate on the "contact_name" field.
func ContactNameNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldContactName, v))
}

// ContactNameIn applies the In predicate on the "contact_name" field.
func ContactNameIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldContactName, vs...))
}

// ContactNameNotIn applies the NotIn predicate on the "contact_name" field.
func ContactNameNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldContactName, vs...))
}

// ContactNameGT applies the GT predicate on the "contact_name" field.
func ContactNameGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldContactName, v))
}

// ContactNameGTE applies the GTE predicate on the "contact_name" field.
func ContactNameGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldContactName, v))
}

// ContactNameLT applies the LT predicate on the "contact_name" field.
func ContactNameLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldContactName, v))
}

// ContactNameLTE applies the LTE predicate on the "contact_name" field.
func ContactNameLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldContactName, v))
}

// ContactNameContains applies the Contains predicate on the "contact_name" field.
func ContactNameContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldContactName, v))
}

// ContactNameHasPrefix applies the HasPrefix predicate on the "contact_name" field.
func ContactNameHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldContactName, v))
}

// ContactNameHasSuffix applies the HasSuffix predicate on the "contact_name" field.
func ContactNameHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldContactName, v))
}

// ContactNameEqualFold applies the EqualFold predicate on the "contact_name" field.
func ContactNameEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldContactName, v))
}

// ContactNameContainsFold applies the ContainsFold predicate on the "contact_name" field.
func ContactNameContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldContactName, v))
}

// ContactPhoneEQ applies the EQ predicate on the "contact_phone" field.
func ContactPhoneEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldContactPhone, v))
}

// ContactPhoneNEQ applies the NEQ predicate on the "contact_phone" field.
func ContactPhoneNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldContactPhone, v))
}

// ContactPhoneIn applies the In predicate on the "contact_phone" field.
func ContactPhoneIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldContactPhone, vs...))
}

// ContactPhoneNotIn applies the NotIn predicate on the "contact_phone" field.
func ContactPhoneNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldContactPhone, vs...))
}

// ContactPhoneGT applies the GT predicate on the "contact_phone" field.
func ContactPhoneGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldContactPhone, v))
}

// ContactPhoneGTE applies the GTE predicate on the "contact_phone" field.
func ContactPhoneGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldContactPhone, v))
}

// ContactPhoneLT applies the LT predicate on the "contact_phone" field.
func ContactPhoneLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldContactPhone, v))
}

// ContactPhoneLTE applies the LTE predicate on the "contact_phone" field.
func ContactPhoneLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldContactPhone, v))
}

// ContactPhoneContains applies the Contains predicate on the "contact_phone" field.
func ContactPhoneContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldContactPhone, v))
}

// ContactPhoneHasPrefix applies the HasPrefix predicate on the "contact_phone" field.
func ContactPhoneHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldContactPhone, v))
}

// ContactPhoneHasSuffix applies the HasSuffix predicate on the "contact_phone" field.
func ContactPhoneHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldContactPhone, v))
}

// ContactPhoneEqualFold applies the EqualFold predicate on the "contact_phone" field.
func ContactPhoneEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldContactPhone, v))
}

// ContactPhoneContainsFold applies the ContainsFold predicate on the "contact_phone" field.
func ContactPhoneContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldContactPhone, v))
}

// ContactEmailEQ applies the EQ predicate on the "contact_email" field.
func ContactEmailEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldContactEmail, v))
}

// ContactEmailNEQ applies the NEQ predicate on the "contact_email" field.
func ContactEmailNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldContactEmail, v))
}

// ContactEmailIn applies the In predicate on the "contact_email" field.
func ContactEmailIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldContactEmail, vs...))
}

// ContactEmailNotIn applies the NotIn predicate on the "contact_email" field.
func ContactEmailNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldContactEmail, vs...))
}

// ContactEmailGT applies the GT predicate on the "contact_email" field.
func ContactEmailGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldContactEmail, v))
}

// ContactEmailGTE applies the GTE predicate on the "contact_email" field.
func ContactEmailGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldContactEmail, v))
}

// ContactEmailLT applies the LT predicate on the "contact_email" field.
func ContactEmailLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldContactEmail, v))
}

// ContactEmailLTE applies the LTE predicate on the "contact_email" field.
func ContactEmailLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldContactEmail, v))
}

// ContactEmailContains applies the Contains predicate on the "contact_email" field.
func ContactEmailContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldContactEmail, v))
}

// ContactEmailHasPrefix applies the HasPrefix predicate on the "contact_email" field.
func ContactEmailHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldContactEmail, v))
}

// ContactEmailHasSuffix applies the HasSuffix predicate on the "contact_email" field.
func ContactEmailHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldContactEmail, v))
}

// ContactEmailEqualFold applies the EqualFold predicate on the "contact_email" field.
func ContactEmailEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldContactEmail, v))
}

// ContactEmailContainsFold applies the ContainsFold predicate on the "contact_email" field.
func ContactEmailContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldContactEmail, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldContainsFold(FieldNotes, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldBalance, v))
}

// TotalRechargedEQ applies the EQ predicate on the "total_recharged" field.
func TotalRechargedEQ(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldTotalRecharged, v))
}

// TotalRechargedNEQ applies the NEQ predicate on the "total_recharged" field.
func TotalRechargedNEQ(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldTotalRecharged, v))
}

// TotalRechargedIn applies the In predicate on the "total_recharged" field.
func TotalRechargedIn(vs ...float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldTotalRecharged, vs...))
}

// TotalRechargedNotIn applies the NotIn predicate on the "total_recharged" field.
func TotalRechargedNotIn(vs ...float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldTotalRecharged, vs...))
}

// TotalRechargedGT applies the GT predicate on the "total_recharged" field.
func TotalRechargedGT(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGT(FieldTotalRecharged, v))
}

// TotalRechargedGTE applies the GTE predicate on the "total_recharged" field.
func TotalRechargedGTE(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldGTE(FieldTotalRecharged, v))
}

// TotalRechargedLT applies the LT predicate on the "total_recharged" field.
func TotalRechargedLT(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLT(FieldTotalRecharged, v))
}

// TotalRechargedLTE applies the LTE predicate on the "total_recharged" field.
func TotalRechargedLTE(v float64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldLTE(FieldTotalRecharged, v))
}

// AdminUserIDEQ applies the EQ predicate on the "admin_user_id" field.
func AdminUserIDEQ(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldEQ(FieldAdminUserID, v))
}

// AdminUserIDNEQ applies the NEQ predicate on the "admin_user_id" field.
func AdminUserIDNEQ(v int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNEQ(FieldAdminUserID, v))
}

// AdminUserIDIn applies the In predicate on the "admin_user_id" field.
func AdminUserIDIn(vs ...int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldIn(FieldAdminUserID, vs...))
}

// AdminUserIDNotIn applies the NotIn predicate on the "admin_user_id" field.
func AdminUserIDNotIn(vs ...int64) predicate.Enterprise {
	return predicate.Enterprise(sql.FieldNotIn(FieldAdminUserID, vs...))
}

// HasAdmin applies the HasEdge predicate on the "admin" edge.
func HasAdmin() predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AdminTable, AdminColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdminWith applies the HasEdge predicate on the "admin" edge with a given conditions (other predicates).
func HasAdminWith(preds ...predicate.User) predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := newAdminStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.EnterpriseMember) predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartments applies the HasEdge predicate on the "departments" edge.
func HasDepartments() predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DepartmentsTable, DepartmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentsWith applies the HasEdge predicate on the "departments" edge with a given conditions (other predicates).
func HasDepartmentsWith(preds ...predicate.Department) predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := newDepartmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscriptions applies the HasEdge predicate on the "subscriptions" edge.
func HasSubscriptions() predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionsTable, SubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionsWith applies the HasEdge predicate on the "subscriptions" edge with a given conditions (other predicates).
func HasSubscriptionsWith(preds ...predicate.EnterpriseSubscription) predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := newSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.Enterprise {
	return predicate.Enterprise(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Enterprise) predicate.Enterprise {
	return predicate.Enterprise(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Enterprise) predicate.Enterprise {
	return predicate.Enterprise(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Enterprise) predicate.Enterprise {
	return predicate.Enterprise(sql.NotPredicates(p))
}
