// Code generated by ent, DO NOT EDIT.

package enterprisesubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// EnterpriseID applies equality check predicate on the "enterprise_id" field. It's identical to EnterpriseIDEQ.
func EnterpriseID(v int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldEnterpriseID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldGroupID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldPlanID, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldExpiresAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldStatus, v))
}

// DailyUsageUsd applies equality check predicate on the "daily_usage_usd" field. It's identical to DailyUsageUsdEQ.
func DailyUsageUsd(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsd applies equality check predicate on the "weekly_usage_usd" field. It's identical to WeeklyUsageUsdEQ.
func WeeklyUsageUsd(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsd applies equality check predicate on the "monthly_usage_usd" field. It's identical to MonthlyUsageUsdEQ.
func MonthlyUsageUsd(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// EnterpriseIDEQ applies the EQ predicate on the "enterprise_id" field.
func EnterpriseIDEQ(v int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldEnterpriseID, v))
}

// EnterpriseIDNEQ applies the NEQ predicate on the "enterprise_id" field.
func EnterpriseIDNEQ(v int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldEnterpriseID, v))
}

// EnterpriseIDIn applies the In predicate on the "enterprise_id" field.
func EnterpriseIDIn(vs ...int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldEnterpriseID, vs...))
}

// EnterpriseIDNotIn applies the NotIn predicate on the "enterprise_id" field.
func EnterpriseIDNotIn(vs ...int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldEnterpriseID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldGroupID, vs...))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldPlanID, vs...))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotNull(FieldExpiresAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldContainsFold(FieldStatus, v))
}

// DailyUsageUsdEQ applies the EQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdEQ(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdNEQ applies the NEQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdNEQ(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdIn applies the In predicate on the "daily_usage_usd" field.
func DailyUsageUsdIn(vs ...float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdNotIn applies the NotIn predicate on the "daily_usage_usd" field.
func DailyUsageUsdNotIn(vs ...float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdGT applies the GT predicate on the "daily_usage_usd" field.
func DailyUsageUsdGT(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdGTE applies the GTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdGTE(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGTE(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLT applies the LT predicate on the "daily_usage_usd" field.
func DailyUsageUsdLT(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLTE applies the LTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdLTE(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLTE(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsdEQ applies the EQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdEQ(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdNEQ applies the NEQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNEQ(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdIn applies the In predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdIn(vs ...float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdNotIn applies the NotIn predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNotIn(vs ...float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdGT applies the GT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGT(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdGTE applies the GTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGTE(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGTE(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLT applies the LT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLT(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLTE applies the LTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLTE(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLTE(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsdEQ applies the EQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdEQ(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdNEQ applies the NEQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNEQ(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdIn applies the In predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdIn(vs ...float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdNotIn applies the NotIn predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNotIn(vs ...float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldNotIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdGT applies the GT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGT(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdGTE applies the GTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGTE(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldGTE(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLT applies the LT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLT(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLTE applies the LTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLTE(v float64) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.FieldLTE(FieldMonthlyUsageUsd, v))
}

// HasEnterprise applies the HasEdge predicate on the "enterprise" edge.
func HasEnterprise() predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EnterpriseTable, EnterpriseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnterpriseWith applies the HasEdge predicate on the "enterprise" edge with a given conditions (other predicates).
func HasEnterpriseWith(preds ...predicate.Enterprise) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(func(s *sql.Selector) {
		step := newEnterpriseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.SubscriptionPlan) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EnterpriseSubscription) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EnterpriseSubscription) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EnterpriseSubscription) predicate.EnterpriseSubscription {
	return predicate.EnterpriseSubscription(sql.NotPredicates(p))
}
