// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/department"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
)

// DepartmentCreate is the builder for creating a Department entity.
type DepartmentCreate struct {
	config
	mutation *DepartmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DepartmentCreate) SetCreatedAt(v time.Time) *DepartmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableCreatedAt(v *time.Time) *DepartmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DepartmentCreate) SetUpdatedAt(v time.Time) *DepartmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableUpdatedAt(v *time.Time) *DepartmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DepartmentCreate) SetDeletedAt(v time.Time) *DepartmentCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableDeletedAt(v *time.Time) *DepartmentCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetEnterpriseID sets the "enterprise_id" field.
func (_c *DepartmentCreate) SetEnterpriseID(v int64) *DepartmentCreate {
	_c.mutation.SetEnterpriseID(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *DepartmentCreate) SetParentID(v int64) *DepartmentCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableParentID(v *int64) *DepartmentCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DepartmentCreate) SetName(v string) *DepartmentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetOrderNum sets the "order_num" field.
func (_c *DepartmentCreate) SetOrderNum(v int) *DepartmentCreate {
	_c.mutation.SetOrderNum(v)
	return _c
}

// SetNillableOrderNum sets the "order_num" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableOrderNum(v *int) *DepartmentCreate {
	if v != nil {
		_c.SetOrderNum(*v)
	}
	return _c
}

// SetLeader sets the "leader" field.
func (_c *DepartmentCreate) SetLeader(v string) *DepartmentCreate {
	_c.mutation.SetLeader(v)
	return _c
}

// SetNillableLeader sets the "leader" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableLeader(v *string) *DepartmentCreate {
	if v != nil {
		_c.SetLeader(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *DepartmentCreate) SetPhone(v string) *DepartmentCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillablePhone(v *string) *DepartmentCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *DepartmentCreate) SetEmail(v string) *DepartmentCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableEmail(v *string) *DepartmentCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DepartmentCreate) SetStatus(v string) *DepartmentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableStatus(v *string) *DepartmentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEnterprise sets the "enterprise" edge to the Enterprise entity.
func (_c *DepartmentCreate) SetEnterprise(v *Enterprise) *DepartmentCreate {
	return _c.SetEnterpriseID(v.ID)
}

// AddMemberIDs adds the "members" edge to the EnterpriseMember entity by IDs.
func (_c *DepartmentCreate) AddMemberIDs(ids ...int64) *DepartmentCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the EnterpriseMember entity.
func (_c *DepartmentCreate) AddMembers(v ...*EnterpriseMember) *DepartmentCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// Mutation returns the DepartmentMutation object of the builder.
func (_c *DepartmentCreate) Mutation() *DepartmentMutation {
	return _c.mutation
}

// Save creates the Department in the database.
func (_c *DepartmentCreate) Save(ctx context.Context) (*Department, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DepartmentCreate) SaveX(ctx context.Context) *Department {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepartmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepartmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DepartmentCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if department.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized department.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := department.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if department.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized department.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := department.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		v := department.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.OrderNum(); !ok {
		v := department.DefaultOrderNum
		_c.mutation.SetOrderNum(v)
	}
	if _, ok := _c.mutation.Leader(); !ok {
		v := department.DefaultLeader
		_c.mutation.SetLeader(v)
	}
	if _, ok := _c.mutation.Phone(); !ok {
		v := department.DefaultPhone
		_c.mutation.SetPhone(v)
	}
	if _, ok := _c.mutation.Email(); !ok {
		v := department.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := department.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *DepartmentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Department.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Department.updated_at"`)}
	}
	if _, ok := _c.mutation.EnterpriseID(); !ok {
		return &ValidationError{Name: "enterprise_id", err: errors.New(`ent: missing required field "Department.enterprise_id"`)}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "Department.parent_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Department.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := department.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Department.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderNum(); !ok {
		return &ValidationError{Name: "order_num", err: errors.New(`ent: missing required field "Department.order_num"`)}
	}
	if _, ok := _c.mutation.Leader(); !ok {
		return &ValidationError{Name: "leader", err: errors.New(`ent: missing required field "Department.leader"`)}
	}
	if v, ok := _c.mutation.Leader(); ok {
		if err := department.LeaderValidator(v); err != nil {
			return &ValidationError{Name: "leader", err: fmt.Errorf(`ent: validator failed for field "Department.leader": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Department.phone"`)}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := department.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Department.phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Department.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := department.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Department.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Department.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := department.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Department.status": %w`, err)}
		}
	}
	if len(_c.mutation.EnterpriseIDs()) == 0 {
		return &ValidationError{Name: "enterprise", err: errors.New(`ent: missing required edge "Department.enterprise"`)}
	}
	return nil
}

func (_c *DepartmentCreate) sqlSave(ctx context.Context) (*Department, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DepartmentCreate) createSpec() (*Department, *sqlgraph.CreateSpec) {
	var (
		_node = &Department{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(department.Table, sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(department.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(department.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(department.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(department.FieldParentID, field.TypeInt64, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(department.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.OrderNum(); ok {
		_spec.SetField(department.FieldOrderNum, field.TypeInt, value)
		_node.OrderNum = value
	}
	if value, ok := _c.mutation.Leader(); ok {
		_spec.SetField(department.FieldLeader, field.TypeString, value)
		_node.Leader = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(department.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(department.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(department.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.EnterpriseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   department.EnterpriseTable,
			Columns: []string{department.EnterpriseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EnterpriseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   department.MembersTable,
			Columns: []string{department.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Department.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DepartmentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DepartmentCreate) OnConflict(opts ...sql.ConflictOption) *DepartmentUpsertOne {
	_c.conflict = opts
	return &DepartmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Department.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DepartmentCreate) OnConflictColumns(columns ...string) *DepartmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DepartmentUpsertOne{
		create: _c,
	}
}

type (
	// DepartmentUpsertOne is the builder for "upsert"-ing
	//  one Department node.
	DepartmentUpsertOne struct {
		create *DepartmentCreate
	}

	// DepartmentUpsert is the "OnConflict" setter.
	DepartmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DepartmentUpsert) SetUpdatedAt(v time.Time) *DepartmentUpsert {
	u.Set(department.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdateUpdatedAt() *DepartmentUpsert {
	u.SetExcluded(department.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DepartmentUpsert) SetDeletedAt(v time.Time) *DepartmentUpsert {
	u.Set(department.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdateDeletedAt() *DepartmentUpsert {
	u.SetExcluded(department.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DepartmentUpsert) ClearDeletedAt() *DepartmentUpsert {
	u.SetNull(department.FieldDeletedAt)
	return u
}

// SetEnterpriseID sets the "enterprise_id" field.
func (u *DepartmentUpsert) SetEnterpriseID(v int64) *DepartmentUpsert {
	u.Set(department.FieldEnterpriseID, v)
	return u
}

// UpdateEnterpriseID sets the "enterprise_id" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdateEnterpriseID() *DepartmentUpsert {
	u.SetExcluded(department.FieldEnterpriseID)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *DepartmentUpsert) SetParentID(v int64) *DepartmentUpsert {
	u.Set(department.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdateParentID() *DepartmentUpsert {
	u.SetExcluded(department.FieldParentID)
	return u
}

// AddParentID adds v to the "parent_id" field.
func (u *DepartmentUpsert) AddParentID(v int64) *DepartmentUpsert {
	u.Add(department.FieldParentID, v)
	return u
}

// SetName sets the "name" field.
func (u *DepartmentUpsert) SetName(v string) *DepartmentUpsert {
	u.Set(department.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdateName() *DepartmentUpsert {
	u.SetExcluded(department.FieldName)
	return u
}

// SetOrderNum sets the "order_num" field.
func (u *DepartmentUpsert) SetOrderNum(v int) *DepartmentUpsert {
	u.Set(department.FieldOrderNum, v)
	return u
}

// UpdateOrderNum sets the "order_num" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdateOrderNum() *DepartmentUpsert {
	u.SetExcluded(department.FieldOrderNum)
	return u
}

// AddOrderNum adds v to the "order_num" field.
func (u *DepartmentUpsert) AddOrderNum(v int) *DepartmentUpsert {
	u.Add(department.FieldOrderNum, v)
	return u
}

// SetLeader sets the "leader" field.
func (u *DepartmentUpsert) SetLeader(v string) *DepartmentUpsert {
	u.Set(department.FieldLeader, v)
	return u
}

// UpdateLeader sets the "leader" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdateLeader() *DepartmentUpsert {
	u.SetExcluded(department.FieldLeader)
	return u
}

// SetPhone sets the "phone" field.
func (u *DepartmentUpsert) SetPhone(v string) *DepartmentUpsert {
	u.Set(department.FieldPhone, v)
	return u
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdatePhone() *DepartmentUpsert {
	u.SetExcluded(department.FieldPhone)
	return u
}

// SetEmail sets the "email" field.
func (u *DepartmentUpsert) SetEmail(v string) *DepartmentUpsert {
	u.Set(department.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdateEmail() *DepartmentUpsert {
	u.SetExcluded(department.FieldEmail)
	return u
}

// SetStatus sets the "status" field.
func (u *DepartmentUpsert) SetStatus(v string) *DepartmentUpsert {
	u.Set(department.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DepartmentUpsert) UpdateStatus() *DepartmentUpsert {
	u.SetExcluded(department.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Department.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DepartmentUpsertOne) UpdateNewValues() *DepartmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(department.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Department.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DepartmentUpsertOne) Ignore() *DepartmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DepartmentUpsertOne) DoNothing() *DepartmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DepartmentCreate.OnConflict
// documentation for more info.
func (u *DepartmentUpsertOne) Update(set func(*DepartmentUpsert)) *DepartmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DepartmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DepartmentUpsertOne) SetUpdatedAt(v time.Time) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdateUpdatedAt() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DepartmentUpsertOne) SetDeletedAt(v time.Time) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdateDeletedAt() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DepartmentUpsertOne) ClearDeletedAt() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEnterpriseID sets the "enterprise_id" field.
func (u *DepartmentUpsertOne) SetEnterpriseID(v int64) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetEnterpriseID(v)
	})
}

// UpdateEnterpriseID sets the "enterprise_id" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdateEnterpriseID() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateEnterpriseID()
	})
}

// SetParentID sets the "parent_id" field.
func (u *DepartmentUpsertOne) SetParentID(v int64) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetParentID(v)
	})
}

// AddParentID adds v to the "parent_id" field.
func (u *DepartmentUpsertOne) AddParentID(v int64) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.AddParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdateParentID() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateParentID()
	})
}

// SetName sets the "name" field.
func (u *DepartmentUpsertOne) SetName(v string) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdateName() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateName()
	})
}

// SetOrderNum sets the "order_num" field.
func (u *DepartmentUpsertOne) SetOrderNum(v int) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetOrderNum(v)
	})
}

// AddOrderNum adds v to the "order_num" field.
func (u *DepartmentUpsertOne) AddOrderNum(v int) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.AddOrderNum(v)
	})
}

// UpdateOrderNum sets the "order_num" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdateOrderNum() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateOrderNum()
	})
}

// SetLeader sets the "leader" field.
func (u *DepartmentUpsertOne) SetLeader(v string) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetLeader(v)
	})
}

// UpdateLeader sets the "leader" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdateLeader() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateLeader()
	})
}

// SetPhone sets the "phone" field.
func (u *DepartmentUpsertOne) SetPhone(v string) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdatePhone() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdatePhone()
	})
}

// SetEmail sets the "email" field.
func (u *DepartmentUpsertOne) SetEmail(v string) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdateEmail() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateEmail()
	})
}

// SetStatus sets the "status" field.
func (u *DepartmentUpsertOne) SetStatus(v string) *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DepartmentUpsertOne) UpdateStatus() *DepartmentUpsertOne {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *DepartmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DepartmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DepartmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DepartmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DepartmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DepartmentCreateBulk is the builder for creating many Department entities in bulk.
type DepartmentCreateBulk struct {
	config
	err      error
	builders []*DepartmentCreate
	conflict []sql.ConflictOption
}

// Save creates the Department entities in the database.
func (_c *DepartmentCreateBulk) Save(ctx context.Context) ([]*Department, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Department, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DepartmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DepartmentCreateBulk) SaveX(ctx context.Context) []*Department {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepartmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepartmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Department.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DepartmentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DepartmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *DepartmentUpsertBulk {
	_c.conflict = opts
	return &DepartmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Department.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DepartmentCreateBulk) OnConflictColumns(columns ...string) *DepartmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DepartmentUpsertBulk{
		create: _c,
	}
}

// DepartmentUpsertBulk is the builder for "upsert"-ing
// a bulk of Department nodes.
type DepartmentUpsertBulk struct {
	create *DepartmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Department.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DepartmentUpsertBulk) UpdateNewValues() *DepartmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(department.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Department.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DepartmentUpsertBulk) Ignore() *DepartmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DepartmentUpsertBulk) DoNothing() *DepartmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DepartmentCreateBulk.OnConflict
// documentation for more info.
func (u *DepartmentUpsertBulk) Update(set func(*DepartmentUpsert)) *DepartmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DepartmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DepartmentUpsertBulk) SetUpdatedAt(v time.Time) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdateUpdatedAt() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DepartmentUpsertBulk) SetDeletedAt(v time.Time) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdateDeletedAt() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DepartmentUpsertBulk) ClearDeletedAt() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEnterpriseID sets the "enterprise_id" field.
func (u *DepartmentUpsertBulk) SetEnterpriseID(v int64) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetEnterpriseID(v)
	})
}

// UpdateEnterpriseID sets the "enterprise_id" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdateEnterpriseID() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateEnterpriseID()
	})
}

// SetParentID sets the "parent_id" field.
func (u *DepartmentUpsertBulk) SetParentID(v int64) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetParentID(v)
	})
}

// AddParentID adds v to the "parent_id" field.
func (u *DepartmentUpsertBulk) AddParentID(v int64) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.AddParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdateParentID() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateParentID()
	})
}

// SetName sets the "name" field.
func (u *DepartmentUpsertBulk) SetName(v string) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdateName() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateName()
	})
}

// SetOrderNum sets the "order_num" field.
func (u *DepartmentUpsertBulk) SetOrderNum(v int) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetOrderNum(v)
	})
}

// AddOrderNum adds v to the "order_num" field.
func (u *DepartmentUpsertBulk) AddOrderNum(v int) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.AddOrderNum(v)
	})
}

// UpdateOrderNum sets the "order_num" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdateOrderNum() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateOrderNum()
	})
}

// SetLeader sets the "leader" field.
func (u *DepartmentUpsertBulk) SetLeader(v string) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetLeader(v)
	})
}

// UpdateLeader sets the "leader" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdateLeader() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateLeader()
	})
}

// SetPhone sets the "phone" field.
func (u *DepartmentUpsertBulk) SetPhone(v string) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdatePhone() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdatePhone()
	})
}

// SetEmail sets the "email" field.
func (u *DepartmentUpsertBulk) SetEmail(v string) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdateEmail() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateEmail()
	})
}

// SetStatus sets the "status" field.
func (u *DepartmentUpsertBulk) SetStatus(v string) *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DepartmentUpsertBulk) UpdateStatus() *DepartmentUpsertBulk {
	return u.Update(func(s *DepartmentUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *DepartmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DepartmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DepartmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DepartmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
