// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
	"github.com/Wei-Shaw/sub2api/ent/enterprisesubscription"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
)

// EnterpriseSubscriptionUpdate is the builder for updating EnterpriseSubscription entities.
type EnterpriseSubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *EnterpriseSubscriptionMutation
}

// Where appends a list predicates to the EnterpriseSubscriptionUpdate builder.
func (_u *EnterpriseSubscriptionUpdate) Where(ps ...predicate.EnterpriseSubscription) *EnterpriseSubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseSubscriptionUpdate) SetUpdatedAt(v time.Time) *EnterpriseSubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEnterpriseID sets the "enterprise_id" field.
func (_u *EnterpriseSubscriptionUpdate) SetEnterpriseID(v int64) *EnterpriseSubscriptionUpdate {
	_u.mutation.SetEnterpriseID(v)
	return _u
}

// SetNillableEnterpriseID sets the "enterprise_id" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdate) SetNillableEnterpriseID(v *int64) *EnterpriseSubscriptionUpdate {
	if v != nil {
		_u.SetEnterpriseID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EnterpriseSubscriptionUpdate) SetGroupID(v int64) *EnterpriseSubscriptionUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdate) SetNillableGroupID(v *int64) *EnterpriseSubscriptionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *EnterpriseSubscriptionUpdate) SetPlanID(v int64) *EnterpriseSubscriptionUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdate) SetNillablePlanID(v *int64) *EnterpriseSubscriptionUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *EnterpriseSubscriptionUpdate) SetStartsAt(v time.Time) *EnterpriseSubscriptionUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdate) SetNillableStartsAt(v *time.Time) *EnterpriseSubscriptionUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EnterpriseSubscriptionUpdate) SetExpiresAt(v time.Time) *EnterpriseSubscriptionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdate) SetNillableExpiresAt(v *time.Time) *EnterpriseSubscriptionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *EnterpriseSubscriptionUpdate) ClearExpiresAt() *EnterpriseSubscriptionUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseSubscriptionUpdate) SetStatus(v string) *EnterpriseSubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdate) SetNillableStatus(v *string) *EnterpriseSubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdate) SetDailyUsageUsd(v float64) *EnterpriseSubscriptionUpdate {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdate) SetNillableDailyUsageUsd(v *float64) *EnterpriseSubscriptionUpdate {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdate) AddDailyUsageUsd(v float64) *EnterpriseSubscriptionUpdate {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdate) SetWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpdate {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdate) SetNillableWeeklyUsageUsd(v *float64) *EnterpriseSubscriptionUpdate {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdate) AddWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpdate {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdate) SetMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdate) SetNillableMonthlyUsageUsd(v *float64) *EnterpriseSubscriptionUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdate) AddMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetEnterprise sets the "enterprise" edge to the Enterprise entity.
func (_u *EnterpriseSubscriptionUpdate) SetEnterprise(v *Enterprise) *EnterpriseSubscriptionUpdate {
	return _u.SetEnterpriseID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EnterpriseSubscriptionUpdate) SetGroup(v *Group) *EnterpriseSubscriptionUpdate {
	return _u.SetGroupID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_u *EnterpriseSubscriptionUpdate) SetPlan(v *SubscriptionPlan) *EnterpriseSubscriptionUpdate {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the EnterpriseSubscriptionMutation object of the builder.
func (_u *EnterpriseSubscriptionUpdate) Mutation() *EnterpriseSubscriptionMutation {
	return _u.mutation
}

// ClearEnterprise clears the "enterprise" edge to the Enterprise entity.
func (_u *EnterpriseSubscriptionUpdate) ClearEnterprise() *EnterpriseSubscriptionUpdate {
	_u.mutation.ClearEnterprise()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EnterpriseSubscriptionUpdate) ClearGroup() *EnterpriseSubscriptionUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearPlan clears the "plan" edge to the SubscriptionPlan entity.
func (_u *EnterpriseSubscriptionUpdate) ClearPlan() *EnterpriseSubscriptionUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnterpriseSubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseSubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnterpriseSubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseSubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseSubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enterprisesubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseSubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprisesubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EnterpriseSubscription.status": %w`, err)}
		}
	}
	if _u.mutation.EnterpriseCleared() && len(_u.mutation.EnterpriseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseSubscription.enterprise"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseSubscription.group"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseSubscription.plan"`)
	}
	return nil
}

func (_u *EnterpriseSubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprisesubscription.Table, enterprisesubscription.Columns, sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisesubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(enterprisesubscription.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(enterprisesubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(enterprisesubscription.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprisesubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(enterprisesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(enterprisesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(enterprisesubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(enterprisesubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(enterprisesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(enterprisesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if _u.mutation.EnterpriseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisesubscription.EnterpriseTable,
			Columns: []string{enterprisesubscription.EnterpriseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnterpriseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisesubscription.EnterpriseTable,
			Columns: []string{enterprisesubscription.EnterpriseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.GroupTable,
			Columns: []string{enterprisesubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.GroupTable,
			Columns: []string{enterprisesubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.PlanTable,
			Columns: []string{enterprisesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.PlanTable,
			Columns: []string{enterprisesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprisesubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnterpriseSubscriptionUpdateOne is the builder for updating a single EnterpriseSubscription entity.
type EnterpriseSubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnterpriseSubscriptionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetUpdatedAt(v time.Time) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEnterpriseID sets the "enterprise_id" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetEnterpriseID(v int64) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.SetEnterpriseID(v)
	return _u
}

// SetNillableEnterpriseID sets the "enterprise_id" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdateOne) SetNillableEnterpriseID(v *int64) *EnterpriseSubscriptionUpdateOne {
	if v != nil {
		_u.SetEnterpriseID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetGroupID(v int64) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdateOne) SetNillableGroupID(v *int64) *EnterpriseSubscriptionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetPlanID(v int64) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdateOne) SetNillablePlanID(v *int64) *EnterpriseSubscriptionUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetStartsAt(v time.Time) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdateOne) SetNillableStartsAt(v *time.Time) *EnterpriseSubscriptionUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetExpiresAt(v time.Time) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdateOne) SetNillableExpiresAt(v *time.Time) *EnterpriseSubscriptionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *EnterpriseSubscriptionUpdateOne) ClearExpiresAt() *EnterpriseSubscriptionUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetStatus(v string) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdateOne) SetNillableStatus(v *string) *EnterpriseSubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetDailyUsageUsd(v float64) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdateOne) SetNillableDailyUsageUsd(v *float64) *EnterpriseSubscriptionUpdateOne {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdateOne) AddDailyUsageUsd(v float64) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdateOne) SetNillableWeeklyUsageUsd(v *float64) *EnterpriseSubscriptionUpdateOne {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdateOne) AddWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdateOne) SetMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *EnterpriseSubscriptionUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *EnterpriseSubscriptionUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *EnterpriseSubscriptionUpdateOne) AddMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetEnterprise sets the "enterprise" edge to the Enterprise entity.
func (_u *EnterpriseSubscriptionUpdateOne) SetEnterprise(v *Enterprise) *EnterpriseSubscriptionUpdateOne {
	return _u.SetEnterpriseID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EnterpriseSubscriptionUpdateOne) SetGroup(v *Group) *EnterpriseSubscriptionUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_u *EnterpriseSubscriptionUpdateOne) SetPlan(v *SubscriptionPlan) *EnterpriseSubscriptionUpdateOne {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the EnterpriseSubscriptionMutation object of the builder.
func (_u *EnterpriseSubscriptionUpdateOne) Mutation() *EnterpriseSubscriptionMutation {
	return _u.mutation
}

// ClearEnterprise clears the "enterprise" edge to the Enterprise entity.
func (_u *EnterpriseSubscriptionUpdateOne) ClearEnterprise() *EnterpriseSubscriptionUpdateOne {
	_u.mutation.ClearEnterprise()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EnterpriseSubscriptionUpdateOne) ClearGroup() *EnterpriseSubscriptionUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearPlan clears the "plan" edge to the SubscriptionPlan entity.
func (_u *EnterpriseSubscriptionUpdateOne) ClearPlan() *EnterpriseSubscriptionUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// Where appends a list predicates to the EnterpriseSubscriptionUpdate builder.
func (_u *EnterpriseSubscriptionUpdateOne) Where(ps ...predicate.EnterpriseSubscription) *EnterpriseSubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnterpriseSubscriptionUpdateOne) Select(field string, fields ...string) *EnterpriseSubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnterpriseSubscription entity.
func (_u *EnterpriseSubscriptionUpdateOne) Save(ctx context.Context) (*EnterpriseSubscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseSubscriptionUpdateOne) SaveX(ctx context.Context) *EnterpriseSubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnterpriseSubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseSubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseSubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enterprisesubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseSubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprisesubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EnterpriseSubscription.status": %w`, err)}
		}
	}
	if _u.mutation.EnterpriseCleared() && len(_u.mutation.EnterpriseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseSubscription.enterprise"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseSubscription.group"`)
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseSubscription.plan"`)
	}
	return nil
}

func (_u *EnterpriseSubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *EnterpriseSubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprisesubscription.Table, enterprisesubscription.Columns, sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EnterpriseSubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enterprisesubscription.FieldID)
		for _, f := range fields {
			if !enterprisesubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enterprisesubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisesubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(enterprisesubscription.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(enterprisesubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(enterprisesubscription.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprisesubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(enterprisesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(enterprisesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(enterprisesubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(enterprisesubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(enterprisesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(enterprisesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if _u.mutation.EnterpriseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisesubscription.EnterpriseTable,
			Columns: []string{enterprisesubscription.EnterpriseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnterpriseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisesubscription.EnterpriseTable,
			Columns: []string{enterprisesubscription.EnterpriseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.GroupTable,
			Columns: []string{enterprisesubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.GroupTable,
			Columns: []string{enterprisesubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.PlanTable,
			Columns: []string{enterprisesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.PlanTable,
			Columns: []string{enterprisesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EnterpriseSubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprisesubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
