// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/department"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisesubscription"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EnterpriseCreate is the builder for creating a Enterprise entity.
type EnterpriseCreate struct {
	config
	mutation *EnterpriseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnterpriseCreate) SetCreatedAt(v time.Time) *EnterpriseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableCreatedAt(v *time.Time) *EnterpriseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnterpriseCreate) SetUpdatedAt(v time.Time) *EnterpriseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableUpdatedAt(v *time.Time) *EnterpriseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EnterpriseCreate) SetDeletedAt(v time.Time) *EnterpriseCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableDeletedAt(v *time.Time) *EnterpriseCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *EnterpriseCreate) SetName(v string) *EnterpriseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetShortName sets the "short_name" field.
func (_c *EnterpriseCreate) SetShortName(v string) *EnterpriseCreate {
	_c.mutation.SetShortName(v)
	return _c
}

// SetNillableShortName sets the "short_name" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableShortName(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetShortName(*v)
	}
	return _c
}

// SetCreditCode sets the "credit_code" field.
func (_c *EnterpriseCreate) SetCreditCode(v string) *EnterpriseCreate {
	_c.mutation.SetCreditCode(v)
	return _c
}

// SetNillableCreditCode sets the "credit_code" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableCreditCode(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetCreditCode(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *EnterpriseCreate) SetAddress(v string) *EnterpriseCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableAddress(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetScale sets the "scale" field.
func (_c *EnterpriseCreate) SetScale(v string) *EnterpriseCreate {
	_c.mutation.SetScale(v)
	return _c
}

// SetNillableScale sets the "scale" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableScale(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetScale(*v)
	}
	return _c
}

// SetIndustry sets the "industry" field.
func (_c *EnterpriseCreate) SetIndustry(v string) *EnterpriseCreate {
	_c.mutation.SetIndustry(v)
	return _c
}

// SetNillableIndustry sets the "industry" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableIndustry(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetIndustry(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *EnterpriseCreate) SetParentID(v int64) *EnterpriseCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableParentID(v *int64) *EnterpriseCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EnterpriseCreate) SetStatus(v string) *EnterpriseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableStatus(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetContactName sets the "contact_name" field.
func (_c *EnterpriseCreate) SetContactName(v string) *EnterpriseCreate {
	_c.mutation.SetContactName(v)
	return _c
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableContactName(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetContactName(*v)
	}
	return _c
}

// SetContactPhone sets the "contact_phone" field.
func (_c *EnterpriseCreate) SetContactPhone(v string) *EnterpriseCreate {
	_c.mutation.SetContactPhone(v)
	return _c
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableContactPhone(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetContactPhone(*v)
	}
	return _c
}

// SetContactEmail sets the "contact_email" field.
func (_c *EnterpriseCreate) SetContactEmail(v string) *EnterpriseCreate {
	_c.mutation.SetContactEmail(v)
	return _c
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableContactEmail(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetContactEmail(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *EnterpriseCreate) SetNotes(v string) *EnterpriseCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableNotes(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *EnterpriseCreate) SetBalance(v float64) *EnterpriseCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableBalance(v *float64) *EnterpriseCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetTotalRecharged sets the "total_recharged" field.
func (_c *EnterpriseCreate) SetTotalRecharged(v float64) *EnterpriseCreate {
	_c.mutation.SetTotalRecharged(v)
	return _c
}

// SetNillableTotalRecharged sets the "total_recharged" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableTotalRecharged(v *float64) *EnterpriseCreate {
	if v != nil {
		_c.SetTotalRecharged(*v)
	}
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *EnterpriseCreate) SetConcurrency(v int) *EnterpriseCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableConcurrency(v *int) *EnterpriseCreate {
	if v != nil {
		_c.SetConcurrency(*v)
	}
	return _c
}

// SetAdminUserID sets the "admin_user_id" field.
func (_c *EnterpriseCreate) SetAdminUserID(v int64) *EnterpriseCreate {
	_c.mutation.SetAdminUserID(v)
	return _c
}

// SetAdminID sets the "admin" edge to the User entity by ID.
func (_c *EnterpriseCreate) SetAdminID(id int64) *EnterpriseCreate {
	_c.mutation.SetAdminID(id)
	return _c
}

// SetAdmin sets the "admin" edge to the User entity.
func (_c *EnterpriseCreate) SetAdmin(v *User) *EnterpriseCreate {
	return _c.SetAdminID(v.ID)
}

// AddMemberIDs adds the "members" edge to the EnterpriseMember entity by IDs.
func (_c *EnterpriseCreate) AddMemberIDs(ids ...int64) *EnterpriseCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the EnterpriseMember entity.
func (_c *EnterpriseCreate) AddMembers(v ...*EnterpriseMember) *EnterpriseCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddDepartmentIDs adds the "departments" edge to the Department entity by IDs.
func (_c *EnterpriseCreate) AddDepartmentIDs(ids ...int64) *EnterpriseCreate {
	_c.mutation.AddDepartmentIDs(ids...)
	return _c
}

// AddDepartments adds the "departments" edges to the Department entity.
func (_c *EnterpriseCreate) AddDepartments(v ...*Department) *EnterpriseCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDepartmentIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the EnterpriseSubscription entity by IDs.
func (_c *EnterpriseCreate) AddSubscriptionIDs(ids ...int64) *EnterpriseCreate {
	_c.mutation.AddSubscriptionIDs(ids...)
	return _c
}

// AddSubscriptions adds the "subscriptions" edges to the EnterpriseSubscription entity.
func (_c *EnterpriseCreate) AddSubscriptions(v ...*EnterpriseSubscription) *EnterpriseCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *EnterpriseCreate) AddUsageLogIDs(ids ...int64) *EnterpriseCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *EnterpriseCreate) AddUsageLogs(v ...*UsageLog) *EnterpriseCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// Mutation returns the EnterpriseMutation object of the builder.
func (_c *EnterpriseCreate) Mutation() *EnterpriseMutation {
	return _c.mutation
}

// Save creates the Enterprise in the database.
func (_c *EnterpriseCreate) Save(ctx context.Context) (*Enterprise, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseCreate) SaveX(ctx context.Context) *Enterprise {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if enterprise.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprise.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := enterprise.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if enterprise.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprise.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprise.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ShortName(); !ok {
		v := enterprise.DefaultShortName
		_c.mutation.SetShortName(v)
	}
	if _, ok := _c.mutation.CreditCode(); !ok {
		v := enterprise.DefaultCreditCode
		_c.mutation.SetCreditCode(v)
	}
	if _, ok := _c.mutation.Address(); !ok {
		v := enterprise.DefaultAddress
		_c.mutation.SetAddress(v)
	}
	if _, ok := _c.mutation.Scale(); !ok {
		v := enterprise.DefaultScale
		_c.mutation.SetScale(v)
	}
	if _, ok := _c.mutation.Industry(); !ok {
		v := enterprise.DefaultIndustry
		_c.mutation.SetIndustry(v)
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		v := enterprise.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := enterprise.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ContactName(); !ok {
		v := enterprise.DefaultContactName
		_c.mutation.SetContactName(v)
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		v := enterprise.DefaultContactPhone
		_c.mutation.SetContactPhone(v)
	}
	if _, ok := _c.mutation.ContactEmail(); !ok {
		v := enterprise.DefaultContactEmail
		_c.mutation.SetContactEmail(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := enterprise.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.Balance(); !ok {
		v := enterprise.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.TotalRecharged(); !ok {
		v := enterprise.DefaultTotalRecharged
		_c.mutation.SetTotalRecharged(v)
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		v := enterprise.DefaultConcurrency
		_c.mutation.SetConcurrency(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Enterprise.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Enterprise.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Enterprise.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := enterprise.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ShortName(); !ok {
		return &ValidationError{Name: "short_name", err: errors.New(`ent: missing required field "Enterprise.short_name"`)}
	}
	if v, ok := _c.mutation.ShortName(); ok {
		if err := enterprise.ShortNameValidator(v); err != nil {
			return &ValidationError{Name: "short_name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.short_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreditCode(); !ok {
		return &ValidationError{Name: "credit_code", err: errors.New(`ent: missing required field "Enterprise.credit_code"`)}
	}
	if v, ok := _c.mutation.CreditCode(); ok {
		if err := enterprise.CreditCodeValidator(v); err != nil {
			return &ValidationError{Name: "credit_code", err: fmt.Errorf(`ent: validator failed for field "Enterprise.credit_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Enterprise.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := enterprise.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Enterprise.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scale(); !ok {
		return &ValidationError{Name: "scale", err: errors.New(`ent: missing required field "Enterprise.scale"`)}
	}
	if v, ok := _c.mutation.Scale(); ok {
		if err := enterprise.ScaleValidator(v); err != nil {
			return &ValidationError{Name: "scale", err: fmt.Errorf(`ent: validator failed for field "Enterprise.scale": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Industry(); !ok {
		return &ValidationError{Name: "industry", err: errors.New(`ent: missing required field "Enterprise.industry"`)}
	}
	if v, ok := _c.mutation.Industry(); ok {
		if err := enterprise.IndustryValidator(v); err != nil {
			return &ValidationError{Name: "industry", err: fmt.Errorf(`ent: validator failed for field "Enterprise.industry": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "Enterprise.parent_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Enterprise.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := enterprise.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Enterprise.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactName(); !ok {
		return &ValidationError{Name: "contact_name", err: errors.New(`ent: missing required field "Enterprise.contact_name"`)}
	}
	if v, ok := _c.mutation.ContactName(); ok {
		if err := enterprise.ContactNameValidator(v); err != nil {
			return &ValidationError{Name: "contact_name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.contact_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		return &ValidationError{Name: "contact_phone", err: errors.New(`ent: missing required field "Enterprise.contact_phone"`)}
	}
	if v, ok := _c.mutation.ContactPhone(); ok {
		if err := enterprise.ContactPhoneValidator(v); err != nil {
			return &ValidationError{Name: "contact_phone", err: fmt.Errorf(`ent: validator failed for field "Enterprise.contact_phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactEmail(); !ok {
		return &ValidationError{Name: "contact_email", err: errors.New(`ent: missing required field "Enterprise.contact_email"`)}
	}
	if v, ok := _c.mutation.ContactEmail(); ok {
		if err := enterprise.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "Enterprise.contact_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "Enterprise.notes"`)}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "Enterprise.balance"`)}
	}
	if _, ok := _c.mutation.TotalRecharged(); !ok {
		return &ValidationError{Name: "total_recharged", err: errors.New(`ent: missing required field "Enterprise.total_recharged"`)}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "Enterprise.concurrency"`)}
	}
	if _, ok := _c.mutation.AdminUserID(); !ok {
		return &ValidationError{Name: "admin_user_id", err: errors.New(`ent: missing required field "Enterprise.admin_user_id"`)}
	}
	if len(_c.mutation.AdminIDs()) == 0 {
		return &ValidationError{Name: "admin", err: errors.New(`ent: missing required edge "Enterprise.admin"`)}
	}
	return nil
}

func (_c *EnterpriseCreate) sqlSave(ctx context.Context) (*Enterprise, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseCreate) createSpec() (*Enterprise, *sqlgraph.CreateSpec) {
	var (
		_node = &Enterprise{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprise.Table, sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enterprise.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprise.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(enterprise.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(enterprise.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ShortName(); ok {
		_spec.SetField(enterprise.FieldShortName, field.TypeString, value)
		_node.ShortName = value
	}
	if value, ok := _c.mutation.CreditCode(); ok {
		_spec.SetField(enterprise.FieldCreditCode, field.TypeString, value)
		_node.CreditCode = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(enterprise.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Scale(); ok {
		_spec.SetField(enterprise.FieldScale, field.TypeString, value)
		_node.Scale = value
	}
	if value, ok := _c.mutation.Industry(); ok {
		_spec.SetField(enterprise.FieldIndustry, field.TypeString, value)
		_node.Industry = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(enterprise.FieldParentID, field.TypeInt64, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(enterprise.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ContactName(); ok {
		_spec.SetField(enterprise.FieldContactName, field.TypeString, value)
		_node.ContactName = value
	}
	if value, ok := _c.mutation.ContactPhone(); ok {
		_spec.SetField(enterprise.FieldContactPhone, field.TypeString, value)
		_node.ContactPhone = value
	}
	if value, ok := _c.mutation.ContactEmail(); ok {
		_spec.SetField(enterprise.FieldContactEmail, field.TypeString, value)
		_node.ContactEmail = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(enterprise.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(enterprise.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.TotalRecharged(); ok {
		_spec.SetField(enterprise.FieldTotalRecharged, field.TypeFloat64, value)
		_node.TotalRecharged = value
	}
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(enterprise.FieldConcurrency, field.TypeInt, value)
		_node.Concurrency = value
	}
	if nodes := _c.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprise.AdminTable,
			Columns: []string{enterprise.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AdminUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.MembersTable,
			Columns: []string{enterprise.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DepartmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.DepartmentsTable,
			Columns: []string{enterprise.DepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.SubscriptionsTable,
			Columns: []string{enterprise.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.UsageLogsTable,
			Columns: []string{enterprise.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Enterprise.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseUpsertOne {
	_c.conflict = opts
	return &EnterpriseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseCreate) OnConflictColumns(columns ...string) *EnterpriseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseUpsertOne is the builder for "upsert"-ing
	//  one Enterprise node.
	EnterpriseUpsertOne struct {
		create *EnterpriseCreate
	}

	// EnterpriseUpsert is the "OnConflict" setter.
	EnterpriseUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseUpsert) SetUpdatedAt(v time.Time) *EnterpriseUpsert {
	u.Set(enterprise.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateUpdatedAt() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseUpsert) SetDeletedAt(v time.Time) *EnterpriseUpsert {
	u.Set(enterprise.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateDeletedAt() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseUpsert) ClearDeletedAt() *EnterpriseUpsert {
	u.SetNull(enterprise.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *EnterpriseUpsert) SetName(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateName() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldName)
	return u
}

// SetShortName sets the "short_name" field.
func (u *EnterpriseUpsert) SetShortName(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldShortName, v)
	return u
}

// UpdateShortName sets the "short_name" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateShortName() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldShortName)
	return u
}

// SetCreditCode sets the "credit_code" field.
func (u *EnterpriseUpsert) SetCreditCode(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldCreditCode, v)
	return u
}

// UpdateCreditCode sets the "credit_code" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateCreditCode() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldCreditCode)
	return u
}

// SetAddress sets the "address" field.
func (u *EnterpriseUpsert) SetAddress(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateAddress() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldAddress)
	return u
}

// SetScale sets the "scale" field.
func (u *EnterpriseUpsert) SetScale(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldScale, v)
	return u
}

// UpdateScale sets the "scale" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateScale() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldScale)
	return u
}

// SetIndustry sets the "industry" field.
func (u *EnterpriseUpsert) SetIndustry(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldIndustry, v)
	return u
}

// UpdateIndustry sets the "industry" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateIndustry() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldIndustry)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *EnterpriseUpsert) SetParentID(v int64) *EnterpriseUpsert {
	u.Set(enterprise.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateParentID() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldParentID)
	return u
}

// AddParentID adds v to the "parent_id" field.
func (u *EnterpriseUpsert) AddParentID(v int64) *EnterpriseUpsert {
	u.Add(enterprise.FieldParentID, v)
	return u
}

// SetStatus sets the "status" field.
func (u *EnterpriseUpsert) SetStatus(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateStatus() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldStatus)
	return u
}

// SetContactName sets the "contact_name" field.
func (u *EnterpriseUpsert) SetContactName(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldContactName, v)
	return u
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateContactName() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldContactName)
	return u
}

// SetContactPhone sets the "contact_phone" field.
func (u *EnterpriseUpsert) SetContactPhone(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldContactPhone, v)
	return u
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateContactPhone() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldContactPhone)
	return u
}

// SetContactEmail sets the "contact_email" field.
func (u *EnterpriseUpsert) SetContactEmail(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldContactEmail, v)
	return u
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateContactEmail() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldContactEmail)
	return u
}

// SetNotes sets the "notes" field.
func (u *EnterpriseUpsert) SetNotes(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateNotes() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldNotes)
	return u
}

// SetBalance sets the "balance" field.
func (u *EnterpriseUpsert) SetBalance(v float64) *EnterpriseUpsert {
	u.Set(enterprise.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateBalance() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *EnterpriseUpsert) AddBalance(v float64) *EnterpriseUpsert {
	u.Add(enterprise.FieldBalance, v)
	return u
}

// SetTotalRecharged sets the "total_recharged" field.
func (u *EnterpriseUpsert) SetTotalRecharged(v float64) *EnterpriseUpsert {
	u.Set(enterprise.FieldTotalRecharged, v)
	return u
}

// UpdateTotalRecharged sets the "total_recharged" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateTotalRecharged() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldTotalRecharged)
	return u
}

// AddTotalRecharged adds v to the "total_recharged" field.
func (u *EnterpriseUpsert) AddTotalRecharged(v float64) *EnterpriseUpsert {
	u.Add(enterprise.FieldTotalRecharged, v)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *EnterpriseUpsert) SetConcurrency(v int) *EnterpriseUpsert {
	u.Set(enterprise.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateConcurrency() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *EnterpriseUpsert) AddConcurrency(v int) *EnterpriseUpsert {
	u.Add(enterprise.FieldConcurrency, v)
	return u
}

// SetAdminUserID sets the "admin_user_id" field.
func (u *EnterpriseUpsert) SetAdminUserID(v int64) *EnterpriseUpsert {
	u.Set(enterprise.FieldAdminUserID, v)
	return u
}

// UpdateAdminUserID sets the "admin_user_id" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateAdminUserID() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldAdminUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseUpsertOne) UpdateNewValues() *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(enterprise.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseUpsertOne) Ignore() *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseUpsertOne) DoNothing() *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseCreate.OnConflict
// documentation for more info.
func (u *EnterpriseUpsertOne) Update(set func(*EnterpriseUpsert)) *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseUpsertOne) SetUpdatedAt(v time.Time) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateUpdatedAt() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseUpsertOne) SetDeletedAt(v time.Time) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateDeletedAt() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseUpsertOne) ClearDeletedAt() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *EnterpriseUpsertOne) SetName(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateName() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateName()
	})
}

// SetShortName sets the "short_name" field.
func (u *EnterpriseUpsertOne) SetShortName(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetShortName(v)
	})
}

// UpdateShortName sets the "short_name" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateShortName() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateShortName()
	})
}

// SetCreditCode sets the "credit_code" field.
func (u *EnterpriseUpsertOne) SetCreditCode(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetCreditCode(v)
	})
}

// UpdateCreditCode sets the "credit_code" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateCreditCode() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateCreditCode()
	})
}

// SetAddress sets the "address" field.
func (u *EnterpriseUpsertOne) SetAddress(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateAddress() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateAddress()
	})
}

// SetScale sets the "scale" field.
func (u *EnterpriseUpsertOne) SetScale(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetScale(v)
	})
}

// UpdateScale sets the "scale" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateScale() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateScale()
	})
}

// SetIndustry sets the "industry" field.
func (u *EnterpriseUpsertOne) SetIndustry(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetIndustry(v)
	})
}

// UpdateIndustry sets the "industry" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateIndustry() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateIndustry()
	})
}

// SetParentID sets the "parent_id" field.
func (u *EnterpriseUpsertOne) SetParentID(v int64) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetParentID(v)
	})
}

// AddParentID adds v to the "parent_id" field.
func (u *EnterpriseUpsertOne) AddParentID(v int64) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.AddParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateParentID() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateParentID()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseUpsertOne) SetStatus(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateStatus() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateStatus()
	})
}

// SetContactName sets the "contact_name" field.
func (u *EnterpriseUpsertOne) SetContactName(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetContactName(v)
	})
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateContactName() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateContactName()
	})
}

// SetContactPhone sets the "contact_phone" field.
func (u *EnterpriseUpsertOne) SetContactPhone(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetContactPhone(v)
	})
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateContactPhone() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateContactPhone()
	})
}

// SetContactEmail sets the "contact_email" field.
func (u *EnterpriseUpsertOne) SetContactEmail(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetContactEmail(v)
	})
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateContactEmail() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateContactEmail()
	})
}

// SetNotes sets the "notes" field.
func (u *EnterpriseUpsertOne) SetNotes(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateNotes() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateNotes()
	})
}

// SetBalance sets the "balance" field.
func (u *EnterpriseUpsertOne) SetBalance(v float64) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *EnterpriseUpsertOne) AddBalance(v float64) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateBalance() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateBalance()
	})
}

// SetTotalRecharged sets the "total_recharged" field.
func (u *EnterpriseUpsertOne) SetTotalRecharged(v float64) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetTotalRecharged(v)
	})
}

// AddTotalRecharged adds v to the "total_recharged" field.
func (u *EnterpriseUpsertOne) AddTotalRecharged(v float64) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.AddTotalRecharged(v)
	})
}

// UpdateTotalRecharged sets the "total_recharged" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateTotalRecharged() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateTotalRecharged()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *EnterpriseUpsertOne) SetConcurrency(v int) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *EnterpriseUpsertOne) AddConcurrency(v int) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateConcurrency() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateConcurrency()
	})
}

// SetAdminUserID sets the "admin_user_id" field.
func (u *EnterpriseUpsertOne) SetAdminUserID(v int64) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetAdminUserID(v)
	})
}

// UpdateAdminUserID sets the "admin_user_id" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateAdminUserID() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateAdminUserID()
	})
}

// Exec executes the query.
func (u *EnterpriseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnterpriseCreateBulk is the builder for creating many Enterprise entities in bulk.
type EnterpriseCreateBulk struct {
	config
	err      error
	builders []*EnterpriseCreate
	conflict []sql.ConflictOption
}

// Save creates the Enterprise entities in the database.
func (_c *EnterpriseCreateBulk) Save(ctx context.Context) ([]*Enterprise, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Enterprise, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseCreateBulk) SaveX(ctx context.Context) []*Enterprise {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Enterprise.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseUpsertBulk {
	_c.conflict = opts
	return &EnterpriseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseCreateBulk) OnConflictColumns(columns ...string) *EnterpriseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseUpsertBulk{
		create: _c,
	}
}

// EnterpriseUpsertBulk is the builder for "upsert"-ing
// a bulk of Enterprise nodes.
type EnterpriseUpsertBulk struct {
	create *EnterpriseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseUpsertBulk) UpdateNewValues() *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(enterprise.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseUpsertBulk) Ignore() *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseUpsertBulk) DoNothing() *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseUpsertBulk) Update(set func(*EnterpriseUpsert)) *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseUpsertBulk) SetUpdatedAt(v time.Time) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateUpdatedAt() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseUpsertBulk) SetDeletedAt(v time.Time) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateDeletedAt() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseUpsertBulk) ClearDeletedAt() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *EnterpriseUpsertBulk) SetName(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateName() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateName()
	})
}

// SetShortName sets the "short_name" field.
func (u *EnterpriseUpsertBulk) SetShortName(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetShortName(v)
	})
}

// UpdateShortName sets the "short_name" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateShortName() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateShortName()
	})
}

// SetCreditCode sets the "credit_code" field.
func (u *EnterpriseUpsertBulk) SetCreditCode(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetCreditCode(v)
	})
}

// UpdateCreditCode sets the "credit_code" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateCreditCode() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateCreditCode()
	})
}

// SetAddress sets the "address" field.
func (u *EnterpriseUpsertBulk) SetAddress(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateAddress() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateAddress()
	})
}

// SetScale sets the "scale" field.
func (u *EnterpriseUpsertBulk) SetScale(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetScale(v)
	})
}

// UpdateScale sets the "scale" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateScale() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateScale()
	})
}

// SetIndustry sets the "industry" field.
func (u *EnterpriseUpsertBulk) SetIndustry(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetIndustry(v)
	})
}

// UpdateIndustry sets the "industry" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateIndustry() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateIndustry()
	})
}

// SetParentID sets the "parent_id" field.
func (u *EnterpriseUpsertBulk) SetParentID(v int64) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetParentID(v)
	})
}

// AddParentID adds v to the "parent_id" field.
func (u *EnterpriseUpsertBulk) AddParentID(v int64) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.AddParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateParentID() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateParentID()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseUpsertBulk) SetStatus(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateStatus() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateStatus()
	})
}

// SetContactName sets the "contact_name" field.
func (u *EnterpriseUpsertBulk) SetContactName(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetContactName(v)
	})
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateContactName() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateContactName()
	})
}

// SetContactPhone sets the "contact_phone" field.
func (u *EnterpriseUpsertBulk) SetContactPhone(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetContactPhone(v)
	})
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateContactPhone() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateContactPhone()
	})
}

// SetContactEmail sets the "contact_email" field.
func (u *EnterpriseUpsertBulk) SetContactEmail(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetContactEmail(v)
	})
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateContactEmail() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateContactEmail()
	})
}

// SetNotes sets the "notes" field.
func (u *EnterpriseUpsertBulk) SetNotes(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateNotes() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateNotes()
	})
}

// SetBalance sets the "balance" field.
func (u *EnterpriseUpsertBulk) SetBalance(v float64) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *EnterpriseUpsertBulk) AddBalance(v float64) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateBalance() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateBalance()
	})
}

// SetTotalRecharged sets the "total_recharged" field.
func (u *EnterpriseUpsertBulk) SetTotalRecharged(v float64) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetTotalRecharged(v)
	})
}

// AddTotalRecharged adds v to the "total_recharged" field.
func (u *EnterpriseUpsertBulk) AddTotalRecharged(v float64) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.AddTotalRecharged(v)
	})
}

// UpdateTotalRecharged sets the "total_recharged" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateTotalRecharged() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateTotalRecharged()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *EnterpriseUpsertBulk) SetConcurrency(v int) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *EnterpriseUpsertBulk) AddConcurrency(v int) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateConcurrency() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateConcurrency()
	})
}

// SetAdminUserID sets the "admin_user_id" field.
func (u *EnterpriseUpsertBulk) SetAdminUserID(v int64) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetAdminUserID(v)
	})
}

// UpdateAdminUserID sets the "admin_user_id" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateAdminUserID() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateAdminUserID()
	})
}

// Exec executes the query.
func (u *EnterpriseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
