// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// Enterprise is the model entity for the Enterprise schema.
type Enterprise struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 企业名称
	Name string `json:"name,omitempty"`
	// 企业简称
	ShortName string `json:"short_name,omitempty"`
	// 统一社会信用代码
	CreditCode string `json:"credit_code,omitempty"`
	// 企业地址
	Address string `json:"address,omitempty"`
	// 企业规模：micro/small/medium/large
	Scale string `json:"scale,omitempty"`
	// 所属行业
	Industry string `json:"industry,omitempty"`
	// 父企业 ID，0=顶级企业
	ParentID int64 `json:"parent_id,omitempty"`
	// active / disabled
	Status string `json:"status,omitempty"`
	// 联系人姓名
	ContactName string `json:"contact_name,omitempty"`
	// 联系人手机号
	ContactPhone string `json:"contact_phone,omitempty"`
	// 联系人邮箱
	ContactEmail string `json:"contact_email,omitempty"`
	// 备注
	Notes string `json:"notes,omitempty"`
	// 企业余额（企业独立资金池）
	Balance float64 `json:"balance,omitempty"`
	// 企业累计充值金额
	TotalRecharged float64 `json:"total_recharged,omitempty"`
	// 企业级并发上限，0=不限制
	Concurrency int `json:"concurrency,omitempty"`
	// 企业管理员对应的 users.id
	AdminUserID int64 `json:"admin_user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EnterpriseQuery when eager-loading is set.
	Edges        EnterpriseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EnterpriseEdges holds the relations/edges for other nodes in the graph.
type EnterpriseEdges struct {
	// Admin holds the value of the admin edge.
	Admin *User `json:"admin,omitempty"`
	// 企业下的所有成员记录
	Members []*EnterpriseMember `json:"members,omitempty"`
	// 企业下的部门
	Departments []*Department `json:"departments,omitempty"`
	// 企业购买的套餐记录
	Subscriptions []*EnterpriseSubscription `json:"subscriptions,omitempty"`
	// 企业维度的用量日志
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// AdminOrErr returns the Admin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnterpriseEdges) AdminOrErr() (*User, error) {
	if e.Admin != nil {
		return e.Admin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "admin"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseEdges) MembersOrErr() ([]*EnterpriseMember, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// DepartmentsOrErr returns the Departments value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseEdges) DepartmentsOrErr() ([]*Department, error) {
	if e.loadedTypes[2] {
		return e.Departments, nil
	}
	return nil, &NotLoadedError{edge: "departments"}
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseEdges) SubscriptionsOrErr() ([]*EnterpriseSubscription, error) {
	if e.loadedTypes[3] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[4] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Enterprise) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case enterprise.FieldBalance, enterprise.FieldTotalRecharged:
			values[i] = new(sql.NullFloat64)
		case enterprise.FieldID, enterprise.FieldParentID, enterprise.FieldConcurrency, enterprise.FieldAdminUserID:
			values[i] = new(sql.NullInt64)
		case enterprise.FieldName, enterprise.FieldShortName, enterprise.FieldCreditCode, enterprise.FieldAddress, enterprise.FieldScale, enterprise.FieldIndustry, enterprise.FieldStatus, enterprise.FieldContactName, enterprise.FieldContactPhone, enterprise.FieldContactEmail, enterprise.FieldNotes:
			values[i] = new(sql.NullString)
		case enterprise.FieldCreatedAt, enterprise.FieldUpdatedAt, enterprise.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Enterprise fields.
func (_m *Enterprise) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case enterprise.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case enterprise.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case enterprise.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case enterprise.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case enterprise.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case enterprise.FieldShortName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field short_name", values[i])
			} else if value.Valid {
				_m.ShortName = value.String
			}
		case enterprise.FieldCreditCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credit_code", values[i])
			} else if value.Valid {
				_m.CreditCode = value.String
			}
		case enterprise.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case enterprise.FieldScale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scale", values[i])
			} else if value.Valid {
				_m.Scale = value.String
			}
		case enterprise.FieldIndustry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field industry", values[i])
			} else if value.Valid {
				_m.Industry = value.String
			}
		case enterprise.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = value.Int64
			}
		case enterprise.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case enterprise.FieldContactName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_name", values[i])
			} else if value.Valid {
				_m.ContactName = value.String
			}
		case enterprise.FieldContactPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_phone", values[i])
			} else if value.Valid {
				_m.ContactPhone = value.String
			}
		case enterprise.FieldContactEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_email", values[i])
			} else if value.Valid {
				_m.ContactEmail = value.String
			}
		case enterprise.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case enterprise.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Float64
			}
		case enterprise.FieldTotalRecharged:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_recharged", values[i])
			} else if value.Valid {
				_m.TotalRecharged = value.Float64
			}
		case enterprise.FieldConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency", values[i])
			} else if value.Valid {
				_m.Concurrency = int(value.Int64)
			}
		case enterprise.FieldAdminUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_user_id", values[i])
			} else if value.Valid {
				_m.AdminUserID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Enterprise.
// This includes values selected through modifiers, order, etc.
func (_m *Enterprise) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAdmin queries the "admin" edge of the Enterprise entity.
func (_m *Enterprise) QueryAdmin() *UserQuery {
	return NewEnterpriseClient(_m.config).QueryAdmin(_m)
}

// QueryMembers queries the "members" edge of the Enterprise entity.
func (_m *Enterprise) QueryMembers() *EnterpriseMemberQuery {
	return NewEnterpriseClient(_m.config).QueryMembers(_m)
}

// QueryDepartments queries the "departments" edge of the Enterprise entity.
func (_m *Enterprise) QueryDepartments() *DepartmentQuery {
	return NewEnterpriseClient(_m.config).QueryDepartments(_m)
}

// QuerySubscriptions queries the "subscriptions" edge of the Enterprise entity.
func (_m *Enterprise) QuerySubscriptions() *EnterpriseSubscriptionQuery {
	return NewEnterpriseClient(_m.config).QuerySubscriptions(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the Enterprise entity.
func (_m *Enterprise) QueryUsageLogs() *UsageLogQuery {
	return NewEnterpriseClient(_m.config).QueryUsageLogs(_m)
}

// Update returns a builder for updating this Enterprise.
// Note that you need to call Enterprise.Unwrap() before calling this method if this Enterprise
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Enterprise) Update() *EnterpriseUpdateOne {
	return NewEnterpriseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Enterprise entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Enterprise) Unwrap() *Enterprise {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Enterprise is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Enterprise) String() string {
	var builder strings.Builder
	builder.WriteString("Enterprise(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("short_name=")
	builder.WriteString(_m.ShortName)
	builder.WriteString(", ")
	builder.WriteString("credit_code=")
	builder.WriteString(_m.CreditCode)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("scale=")
	builder.WriteString(_m.Scale)
	builder.WriteString(", ")
	builder.WriteString("industry=")
	builder.WriteString(_m.Industry)
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("contact_name=")
	builder.WriteString(_m.ContactName)
	builder.WriteString(", ")
	builder.WriteString("contact_phone=")
	builder.WriteString(_m.ContactPhone)
	builder.WriteString(", ")
	builder.WriteString("contact_email=")
	builder.WriteString(_m.ContactEmail)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("total_recharged=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalRecharged))
	builder.WriteString(", ")
	builder.WriteString("concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concurrency))
	builder.WriteString(", ")
	builder.WriteString("admin_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdminUserID))
	builder.WriteByte(')')
	return builder.String()
}

// Enterprises is a parsable slice of Enterprise.
type Enterprises []*Enterprise
