// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterprisesubscription"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EnterpriseSubscriptionDelete is the builder for deleting a EnterpriseSubscription entity.
type EnterpriseSubscriptionDelete struct {
	config
	hooks    []Hook
	mutation *EnterpriseSubscriptionMutation
}

// Where appends a list predicates to the EnterpriseSubscriptionDelete builder.
func (_d *EnterpriseSubscriptionDelete) Where(ps ...predicate.EnterpriseSubscription) *EnterpriseSubscriptionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EnterpriseSubscriptionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnterpriseSubscriptionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EnterpriseSubscriptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(enterprisesubscription.Table, sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EnterpriseSubscriptionDeleteOne is the builder for deleting a single EnterpriseSubscription entity.
type EnterpriseSubscriptionDeleteOne struct {
	_d *EnterpriseSubscriptionDelete
}

// Where appends a list predicates to the EnterpriseSubscriptionDelete builder.
func (_d *EnterpriseSubscriptionDeleteOne) Where(ps ...predicate.EnterpriseSubscription) *EnterpriseSubscriptionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EnterpriseSubscriptionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{enterprisesubscription.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnterpriseSubscriptionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
