// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
	"github.com/Wei-Shaw/sub2api/ent/enterprisesubscription"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
)

// EnterpriseSubscriptionCreate is the builder for creating a EnterpriseSubscription entity.
type EnterpriseSubscriptionCreate struct {
	config
	mutation *EnterpriseSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnterpriseSubscriptionCreate) SetCreatedAt(v time.Time) *EnterpriseSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnterpriseSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *EnterpriseSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnterpriseSubscriptionCreate) SetUpdatedAt(v time.Time) *EnterpriseSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnterpriseSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *EnterpriseSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEnterpriseID sets the "enterprise_id" field.
func (_c *EnterpriseSubscriptionCreate) SetEnterpriseID(v int64) *EnterpriseSubscriptionCreate {
	_c.mutation.SetEnterpriseID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *EnterpriseSubscriptionCreate) SetGroupID(v int64) *EnterpriseSubscriptionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *EnterpriseSubscriptionCreate) SetPlanID(v int64) *EnterpriseSubscriptionCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *EnterpriseSubscriptionCreate) SetStartsAt(v time.Time) *EnterpriseSubscriptionCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EnterpriseSubscriptionCreate) SetExpiresAt(v time.Time) *EnterpriseSubscriptionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *EnterpriseSubscriptionCreate) SetNillableExpiresAt(v *time.Time) *EnterpriseSubscriptionCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EnterpriseSubscriptionCreate) SetStatus(v string) *EnterpriseSubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EnterpriseSubscriptionCreate) SetNillableStatus(v *string) *EnterpriseSubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *EnterpriseSubscriptionCreate) SetDailyUsageUsd(v float64) *EnterpriseSubscriptionCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *EnterpriseSubscriptionCreate) SetNillableDailyUsageUsd(v *float64) *EnterpriseSubscriptionCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_c *EnterpriseSubscriptionCreate) SetWeeklyUsageUsd(v float64) *EnterpriseSubscriptionCreate {
	_c.mutation.SetWeeklyUsageUsd(v)
	return _c
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_c *EnterpriseSubscriptionCreate) SetNillableWeeklyUsageUsd(v *float64) *EnterpriseSubscriptionCreate {
	if v != nil {
		_c.SetWeeklyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *EnterpriseSubscriptionCreate) SetMonthlyUsageUsd(v float64) *EnterpriseSubscriptionCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *EnterpriseSubscriptionCreate) SetNillableMonthlyUsageUsd(v *float64) *EnterpriseSubscriptionCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetEnterprise sets the "enterprise" edge to the Enterprise entity.
func (_c *EnterpriseSubscriptionCreate) SetEnterprise(v *Enterprise) *EnterpriseSubscriptionCreate {
	return _c.SetEnterpriseID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *EnterpriseSubscriptionCreate) SetGroup(v *Group) *EnterpriseSubscriptionCreate {
	return _c.SetGroupID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_c *EnterpriseSubscriptionCreate) SetPlan(v *SubscriptionPlan) *EnterpriseSubscriptionCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the EnterpriseSubscriptionMutation object of the builder.
func (_c *EnterpriseSubscriptionCreate) Mutation() *EnterpriseSubscriptionMutation {
	return _c.mutation
}

// Save creates the EnterpriseSubscription in the database.
func (_c *EnterpriseSubscriptionCreate) Save(ctx context.Context) (*EnterpriseSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseSubscriptionCreate) SaveX(ctx context.Context) *EnterpriseSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := enterprisesubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := enterprisesubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := enterprisesubscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := enterprisesubscription.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		v := enterprisesubscription.DefaultWeeklyUsageUsd
		_c.mutation.SetWeeklyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := enterprisesubscription.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseSubscriptionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnterpriseSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EnterpriseSubscription.updated_at"`)}
	}
	if _, ok := _c.mutation.EnterpriseID(); !ok {
		return &ValidationError{Name: "enterprise_id", err: errors.New(`ent: missing required field "EnterpriseSubscription.enterprise_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "EnterpriseSubscription.group_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "EnterpriseSubscription.plan_id"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "EnterpriseSubscription.starts_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EnterpriseSubscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := enterprisesubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EnterpriseSubscription.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "EnterpriseSubscription.daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		return &ValidationError{Name: "weekly_usage_usd", err: errors.New(`ent: missing required field "EnterpriseSubscription.weekly_usage_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "EnterpriseSubscription.monthly_usage_usd"`)}
	}
	if len(_c.mutation.EnterpriseIDs()) == 0 {
		return &ValidationError{Name: "enterprise", err: errors.New(`ent: missing required edge "EnterpriseSubscription.enterprise"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "EnterpriseSubscription.group"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "EnterpriseSubscription.plan"`)}
	}
	return nil
}

func (_c *EnterpriseSubscriptionCreate) sqlSave(ctx context.Context) (*EnterpriseSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseSubscriptionCreate) createSpec() (*EnterpriseSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &EnterpriseSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprisesubscription.Table, sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enterprisesubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisesubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(enterprisesubscription.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(enterprisesubscription.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(enterprisesubscription.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(enterprisesubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(enterprisesubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
		_node.WeeklyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(enterprisesubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if nodes := _c.mutation.EnterpriseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisesubscription.EnterpriseTable,
			Columns: []string{enterprisesubscription.EnterpriseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EnterpriseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.GroupTable,
			Columns: []string{enterprisesubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisesubscription.PlanTable,
			Columns: []string{enterprisesubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseSubscription.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseSubscriptionUpsertOne {
	_c.conflict = opts
	return &EnterpriseSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseSubscriptionCreate) OnConflictColumns(columns ...string) *EnterpriseSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one EnterpriseSubscription node.
	EnterpriseSubscriptionUpsertOne struct {
		create *EnterpriseSubscriptionCreate
	}

	// EnterpriseSubscriptionUpsert is the "OnConflict" setter.
	EnterpriseSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseSubscriptionUpsert) SetUpdatedAt(v time.Time) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdateUpdatedAt() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldUpdatedAt)
	return u
}

// SetEnterpriseID sets the "enterprise_id" field.
func (u *EnterpriseSubscriptionUpsert) SetEnterpriseID(v int64) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldEnterpriseID, v)
	return u
}

// UpdateEnterpriseID sets the "enterprise_id" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdateEnterpriseID() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldEnterpriseID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *EnterpriseSubscriptionUpsert) SetGroupID(v int64) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdateGroupID() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldGroupID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *EnterpriseSubscriptionUpsert) SetPlanID(v int64) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdatePlanID() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldPlanID)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *EnterpriseSubscriptionUpsert) SetStartsAt(v time.Time) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdateStartsAt() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *EnterpriseSubscriptionUpsert) SetExpiresAt(v time.Time) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdateExpiresAt() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *EnterpriseSubscriptionUpsert) ClearExpiresAt() *EnterpriseSubscriptionUpsert {
	u.SetNull(enterprisesubscription.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *EnterpriseSubscriptionUpsert) SetStatus(v string) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdateStatus() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldStatus)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *EnterpriseSubscriptionUpsert) SetDailyUsageUsd(v float64) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdateDailyUsageUsd() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *EnterpriseSubscriptionUpsert) AddDailyUsageUsd(v float64) *EnterpriseSubscriptionUpsert {
	u.Add(enterprisesubscription.FieldDailyUsageUsd, v)
	return u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsert) SetWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldWeeklyUsageUsd, v)
	return u
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdateWeeklyUsageUsd() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldWeeklyUsageUsd)
	return u
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsert) AddWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpsert {
	u.Add(enterprisesubscription.FieldWeeklyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsert) SetMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpsert {
	u.Set(enterprisesubscription.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsert) UpdateMonthlyUsageUsd() *EnterpriseSubscriptionUpsert {
	u.SetExcluded(enterprisesubscription.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsert) AddMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpsert {
	u.Add(enterprisesubscription.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EnterpriseSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseSubscriptionUpsertOne) UpdateNewValues() *EnterpriseSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(enterprisesubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseSubscriptionUpsertOne) Ignore() *EnterpriseSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseSubscriptionUpsertOne) DoNothing() *EnterpriseSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseSubscriptionCreate.OnConflict
// documentation for more info.
func (u *EnterpriseSubscriptionUpsertOne) Update(set func(*EnterpriseSubscriptionUpsert)) *EnterpriseSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdateUpdatedAt() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEnterpriseID sets the "enterprise_id" field.
func (u *EnterpriseSubscriptionUpsertOne) SetEnterpriseID(v int64) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetEnterpriseID(v)
	})
}

// UpdateEnterpriseID sets the "enterprise_id" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdateEnterpriseID() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateEnterpriseID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EnterpriseSubscriptionUpsertOne) SetGroupID(v int64) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdateGroupID() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateGroupID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *EnterpriseSubscriptionUpsertOne) SetPlanID(v int64) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdatePlanID() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *EnterpriseSubscriptionUpsertOne) SetStartsAt(v time.Time) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdateStartsAt() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EnterpriseSubscriptionUpsertOne) SetExpiresAt(v time.Time) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdateExpiresAt() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *EnterpriseSubscriptionUpsertOne) ClearExpiresAt() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.ClearExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseSubscriptionUpsertOne) SetStatus(v string) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdateStatus() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertOne) SetDailyUsageUsd(v float64) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertOne) AddDailyUsageUsd(v float64) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdateDailyUsageUsd() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertOne) SetWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertOne) AddWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdateWeeklyUsageUsd() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertOne) SetMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertOne) AddMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertOne) UpdateMonthlyUsageUsd() *EnterpriseSubscriptionUpsertOne {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// Exec executes the query.
func (u *EnterpriseSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseSubscriptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseSubscriptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnterpriseSubscriptionCreateBulk is the builder for creating many EnterpriseSubscription entities in bulk.
type EnterpriseSubscriptionCreateBulk struct {
	config
	err      error
	builders []*EnterpriseSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the EnterpriseSubscription entities in the database.
func (_c *EnterpriseSubscriptionCreateBulk) Save(ctx context.Context) ([]*EnterpriseSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnterpriseSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseSubscriptionCreateBulk) SaveX(ctx context.Context) []*EnterpriseSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseSubscriptionUpsertBulk {
	_c.conflict = opts
	return &EnterpriseSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseSubscriptionCreateBulk) OnConflictColumns(columns ...string) *EnterpriseSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseSubscriptionUpsertBulk{
		create: _c,
	}
}

// EnterpriseSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of EnterpriseSubscription nodes.
type EnterpriseSubscriptionUpsertBulk struct {
	create *EnterpriseSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EnterpriseSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseSubscriptionUpsertBulk) UpdateNewValues() *EnterpriseSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(enterprisesubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseSubscriptionUpsertBulk) Ignore() *EnterpriseSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseSubscriptionUpsertBulk) DoNothing() *EnterpriseSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseSubscriptionUpsertBulk) Update(set func(*EnterpriseSubscriptionUpsert)) *EnterpriseSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdateUpdatedAt() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEnterpriseID sets the "enterprise_id" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetEnterpriseID(v int64) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetEnterpriseID(v)
	})
}

// UpdateEnterpriseID sets the "enterprise_id" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdateEnterpriseID() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateEnterpriseID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetGroupID(v int64) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdateGroupID() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateGroupID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetPlanID(v int64) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdatePlanID() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetStartsAt(v time.Time) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdateStartsAt() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetExpiresAt(v time.Time) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdateExpiresAt() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *EnterpriseSubscriptionUpsertBulk) ClearExpiresAt() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.ClearExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetStatus(v string) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdateStatus() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetDailyUsageUsd(v float64) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertBulk) AddDailyUsageUsd(v float64) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdateDailyUsageUsd() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertBulk) AddWeeklyUsageUsd(v float64) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdateWeeklyUsageUsd() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertBulk) SetMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *EnterpriseSubscriptionUpsertBulk) AddMonthlyUsageUsd(v float64) *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *EnterpriseSubscriptionUpsertBulk) UpdateMonthlyUsageUsd() *EnterpriseSubscriptionUpsertBulk {
	return u.Update(func(s *EnterpriseSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// Exec executes the query.
func (u *EnterpriseSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
