// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/department"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EnterpriseMemberCreate is the builder for creating a EnterpriseMember entity.
type EnterpriseMemberCreate struct {
	config
	mutation *EnterpriseMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnterpriseMemberCreate) SetCreatedAt(v time.Time) *EnterpriseMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableCreatedAt(v *time.Time) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnterpriseMemberCreate) SetUpdatedAt(v time.Time) *EnterpriseMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableUpdatedAt(v *time.Time) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EnterpriseMemberCreate) SetDeletedAt(v time.Time) *EnterpriseMemberCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableDeletedAt(v *time.Time) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetEnterpriseID sets the "enterprise_id" field.
func (_c *EnterpriseMemberCreate) SetEnterpriseID(v int64) *EnterpriseMemberCreate {
	_c.mutation.SetEnterpriseID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *EnterpriseMemberCreate) SetUserID(v int64) *EnterpriseMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *EnterpriseMemberCreate) SetRole(v string) *EnterpriseMemberCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableRole(v *string) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EnterpriseMemberCreate) SetStatus(v string) *EnterpriseMemberCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableStatus(v *string) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *EnterpriseMemberCreate) SetDepartmentID(v int64) *EnterpriseMemberCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableDepartmentID(v *int64) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetDepartmentID(*v)
	}
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *EnterpriseMemberCreate) SetConcurrency(v int) *EnterpriseMemberCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableConcurrency(v *int) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetConcurrency(*v)
	}
	return _c
}

// SetRpmLimit sets the "rpm_limit" field.
func (_c *EnterpriseMemberCreate) SetRpmLimit(v int) *EnterpriseMemberCreate {
	_c.mutation.SetRpmLimit(v)
	return _c
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableRpmLimit(v *int) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetRpmLimit(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *EnterpriseMemberCreate) SetNotes(v string) *EnterpriseMemberCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableNotes(v *string) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *EnterpriseMemberCreate) SetJoinedAt(v time.Time) *EnterpriseMemberCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableJoinedAt(v *time.Time) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetUnboundAt sets the "unbound_at" field.
func (_c *EnterpriseMemberCreate) SetUnboundAt(v time.Time) *EnterpriseMemberCreate {
	_c.mutation.SetUnboundAt(v)
	return _c
}

// SetNillableUnboundAt sets the "unbound_at" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableUnboundAt(v *time.Time) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetUnboundAt(*v)
	}
	return _c
}

// SetEnterprise sets the "enterprise" edge to the Enterprise entity.
func (_c *EnterpriseMemberCreate) SetEnterprise(v *Enterprise) *EnterpriseMemberCreate {
	return _c.SetEnterpriseID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *EnterpriseMemberCreate) SetUser(v *User) *EnterpriseMemberCreate {
	return _c.SetUserID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_c *EnterpriseMemberCreate) SetDepartment(v *Department) *EnterpriseMemberCreate {
	return _c.SetDepartmentID(v.ID)
}

// AddAssignedKeyIDs adds the "assigned_keys" edge to the APIKey entity by IDs.
func (_c *EnterpriseMemberCreate) AddAssignedKeyIDs(ids ...int64) *EnterpriseMemberCreate {
	_c.mutation.AddAssignedKeyIDs(ids...)
	return _c
}

// AddAssignedKeys adds the "assigned_keys" edges to the APIKey entity.
func (_c *EnterpriseMemberCreate) AddAssignedKeys(v ...*APIKey) *EnterpriseMemberCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssignedKeyIDs(ids...)
}

// Mutation returns the EnterpriseMemberMutation object of the builder.
func (_c *EnterpriseMemberCreate) Mutation() *EnterpriseMemberMutation {
	return _c.mutation
}

// Save creates the EnterpriseMember in the database.
func (_c *EnterpriseMemberCreate) Save(ctx context.Context) (*EnterpriseMember, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseMemberCreate) SaveX(ctx context.Context) *EnterpriseMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseMemberCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if enterprisemember.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprisemember.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := enterprisemember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if enterprisemember.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprisemember.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprisemember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := enterprisemember.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := enterprisemember.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		v := enterprisemember.DefaultConcurrency
		_c.mutation.SetConcurrency(v)
	}
	if _, ok := _c.mutation.RpmLimit(); !ok {
		v := enterprisemember.DefaultRpmLimit
		_c.mutation.SetRpmLimit(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := enterprisemember.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		if enterprisemember.DefaultJoinedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprisemember.DefaultJoinedAt (forgotten import ent/runtime?)")
		}
		v := enterprisemember.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnterpriseMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EnterpriseMember.updated_at"`)}
	}
	if _, ok := _c.mutation.EnterpriseID(); !ok {
		return &ValidationError{Name: "enterprise_id", err: errors.New(`ent: missing required field "EnterpriseMember.enterprise_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "EnterpriseMember.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "EnterpriseMember.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := enterprisemember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EnterpriseMember.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := enterprisemember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "EnterpriseMember.concurrency"`)}
	}
	if _, ok := _c.mutation.RpmLimit(); !ok {
		return &ValidationError{Name: "rpm_limit", err: errors.New(`ent: missing required field "EnterpriseMember.rpm_limit"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "EnterpriseMember.notes"`)}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "EnterpriseMember.joined_at"`)}
	}
	if len(_c.mutation.EnterpriseIDs()) == 0 {
		return &ValidationError{Name: "enterprise", err: errors.New(`ent: missing required edge "EnterpriseMember.enterprise"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "EnterpriseMember.user"`)}
	}
	return nil
}

func (_c *EnterpriseMemberCreate) sqlSave(ctx context.Context) (*EnterpriseMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseMemberCreate) createSpec() (*EnterpriseMember, *sqlgraph.CreateSpec) {
	var (
		_node = &EnterpriseMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprisemember.Table, sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enterprisemember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisemember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(enterprisemember.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(enterprisemember.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(enterprisemember.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(enterprisemember.FieldConcurrency, field.TypeInt, value)
		_node.Concurrency = value
	}
	if value, ok := _c.mutation.RpmLimit(); ok {
		_spec.SetField(enterprisemember.FieldRpmLimit, field.TypeInt, value)
		_node.RpmLimit = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(enterprisemember.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(enterprisemember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if value, ok := _c.mutation.UnboundAt(); ok {
		_spec.SetField(enterprisemember.FieldUnboundAt, field.TypeTime, value)
		_node.UnboundAt = &value
	}
	if nodes := _c.mutation.EnterpriseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisemember.EnterpriseTable,
			Columns: []string{enterprisemember.EnterpriseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EnterpriseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisemember.UserTable,
			Columns: []string{enterprisemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisemember.DepartmentTable,
			Columns: []string{enterprisemember.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DepartmentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignedKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.AssignedKeysTable,
			Columns: []string{enterprisemember.AssignedKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberUpsertOne {
	_c.conflict = opts
	return &EnterpriseMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberCreate) OnConflictColumns(columns ...string) *EnterpriseMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseMemberUpsertOne is the builder for "upsert"-ing
	//  one EnterpriseMember node.
	EnterpriseMemberUpsertOne struct {
		create *EnterpriseMemberCreate
	}

	// EnterpriseMemberUpsert is the "OnConflict" setter.
	EnterpriseMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberUpsert) SetUpdatedAt(v time.Time) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateUpdatedAt() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseMemberUpsert) SetDeletedAt(v time.Time) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateDeletedAt() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseMemberUpsert) ClearDeletedAt() *EnterpriseMemberUpsert {
	u.SetNull(enterprisemember.FieldDeletedAt)
	return u
}

// SetEnterpriseID sets the "enterprise_id" field.
func (u *EnterpriseMemberUpsert) SetEnterpriseID(v int64) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldEnterpriseID, v)
	return u
}

// UpdateEnterpriseID sets the "enterprise_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateEnterpriseID() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldEnterpriseID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *EnterpriseMemberUpsert) SetUserID(v int64) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateUserID() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldUserID)
	return u
}

// SetRole sets the "role" field.
func (u *EnterpriseMemberUpsert) SetRole(v string) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateRole() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldRole)
	return u
}

// SetStatus sets the "status" field.
func (u *EnterpriseMemberUpsert) SetStatus(v string) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateStatus() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldStatus)
	return u
}

// SetDepartmentID sets the "department_id" field.
func (u *EnterpriseMemberUpsert) SetDepartmentID(v int64) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldDepartmentID, v)
	return u
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateDepartmentID() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldDepartmentID)
	return u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (u *EnterpriseMemberUpsert) ClearDepartmentID() *EnterpriseMemberUpsert {
	u.SetNull(enterprisemember.FieldDepartmentID)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *EnterpriseMemberUpsert) SetConcurrency(v int) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateConcurrency() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *EnterpriseMemberUpsert) AddConcurrency(v int) *EnterpriseMemberUpsert {
	u.Add(enterprisemember.FieldConcurrency, v)
	return u
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *EnterpriseMemberUpsert) SetRpmLimit(v int) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldRpmLimit, v)
	return u
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateRpmLimit() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldRpmLimit)
	return u
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *EnterpriseMemberUpsert) AddRpmLimit(v int) *EnterpriseMemberUpsert {
	u.Add(enterprisemember.FieldRpmLimit, v)
	return u
}

// SetNotes sets the "notes" field.
func (u *EnterpriseMemberUpsert) SetNotes(v string) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateNotes() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldNotes)
	return u
}

// SetUnboundAt sets the "unbound_at" field.
func (u *EnterpriseMemberUpsert) SetUnboundAt(v time.Time) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldUnboundAt, v)
	return u
}

// UpdateUnboundAt sets the "unbound_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateUnboundAt() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldUnboundAt)
	return u
}

// ClearUnboundAt clears the value of the "unbound_at" field.
func (u *EnterpriseMemberUpsert) ClearUnboundAt() *EnterpriseMemberUpsert {
	u.SetNull(enterprisemember.FieldUnboundAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberUpsertOne) UpdateNewValues() *EnterpriseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(enterprisemember.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.JoinedAt(); exists {
			s.SetIgnore(enterprisemember.FieldJoinedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseMemberUpsertOne) Ignore() *EnterpriseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberUpsertOne) DoNothing() *EnterpriseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberCreate.OnConflict
// documentation for more info.
func (u *EnterpriseMemberUpsertOne) Update(set func(*EnterpriseMemberUpsert)) *EnterpriseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberUpsertOne) SetUpdatedAt(v time.Time) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateUpdatedAt() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseMemberUpsertOne) SetDeletedAt(v time.Time) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateDeletedAt() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseMemberUpsertOne) ClearDeletedAt() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEnterpriseID sets the "enterprise_id" field.
func (u *EnterpriseMemberUpsertOne) SetEnterpriseID(v int64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetEnterpriseID(v)
	})
}

// UpdateEnterpriseID sets the "enterprise_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateEnterpriseID() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateEnterpriseID()
	})
}

// SetUserID sets the "user_id" field.
func (u *EnterpriseMemberUpsertOne) SetUserID(v int64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateUserID() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *EnterpriseMemberUpsertOne) SetRole(v string) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateRole() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRole()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseMemberUpsertOne) SetStatus(v string) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateStatus() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateStatus()
	})
}

// SetDepartmentID sets the "department_id" field.
func (u *EnterpriseMemberUpsertOne) SetDepartmentID(v int64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetDepartmentID(v)
	})
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateDepartmentID() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateDepartmentID()
	})
}

// ClearDepartmentID clears the value of the "department_id" field.
func (u *EnterpriseMemberUpsertOne) ClearDepartmentID() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.ClearDepartmentID()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *EnterpriseMemberUpsertOne) SetConcurrency(v int) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *EnterpriseMemberUpsertOne) AddConcurrency(v int) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateConcurrency() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateConcurrency()
	})
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *EnterpriseMemberUpsertOne) SetRpmLimit(v int) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRpmLimit(v)
	})
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *EnterpriseMemberUpsertOne) AddRpmLimit(v int) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddRpmLimit(v)
	})
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateRpmLimit() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRpmLimit()
	})
}

// SetNotes sets the "notes" field.
func (u *EnterpriseMemberUpsertOne) SetNotes(v string) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateNotes() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateNotes()
	})
}

// SetUnboundAt sets the "unbound_at" field.
func (u *EnterpriseMemberUpsertOne) SetUnboundAt(v time.Time) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetUnboundAt(v)
	})
}

// UpdateUnboundAt sets the "unbound_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateUnboundAt() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateUnboundAt()
	})
}

// ClearUnboundAt clears the value of the "unbound_at" field.
func (u *EnterpriseMemberUpsertOne) ClearUnboundAt() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.ClearUnboundAt()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseMemberUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseMemberUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnterpriseMemberCreateBulk is the builder for creating many EnterpriseMember entities in bulk.
type EnterpriseMemberCreateBulk struct {
	config
	err      error
	builders []*EnterpriseMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the EnterpriseMember entities in the database.
func (_c *EnterpriseMemberCreateBulk) Save(ctx context.Context) ([]*EnterpriseMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnterpriseMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseMemberCreateBulk) SaveX(ctx context.Context) []*EnterpriseMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberUpsertBulk {
	_c.conflict = opts
	return &EnterpriseMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberCreateBulk) OnConflictColumns(columns ...string) *EnterpriseMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberUpsertBulk{
		create: _c,
	}
}

// EnterpriseMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of EnterpriseMember nodes.
type EnterpriseMemberUpsertBulk struct {
	create *EnterpriseMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberUpsertBulk) UpdateNewValues() *EnterpriseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(enterprisemember.FieldCreatedAt)
			}
			if _, exists := b.mutation.JoinedAt(); exists {
				s.SetIgnore(enterprisemember.FieldJoinedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseMemberUpsertBulk) Ignore() *EnterpriseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberUpsertBulk) DoNothing() *EnterpriseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseMemberUpsertBulk) Update(set func(*EnterpriseMemberUpsert)) *EnterpriseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberUpsertBulk) SetUpdatedAt(v time.Time) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateUpdatedAt() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseMemberUpsertBulk) SetDeletedAt(v time.Time) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateDeletedAt() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseMemberUpsertBulk) ClearDeletedAt() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEnterpriseID sets the "enterprise_id" field.
func (u *EnterpriseMemberUpsertBulk) SetEnterpriseID(v int64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetEnterpriseID(v)
	})
}

// UpdateEnterpriseID sets the "enterprise_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateEnterpriseID() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateEnterpriseID()
	})
}

// SetUserID sets the "user_id" field.
func (u *EnterpriseMemberUpsertBulk) SetUserID(v int64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateUserID() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *EnterpriseMemberUpsertBulk) SetRole(v string) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateRole() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRole()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseMemberUpsertBulk) SetStatus(v string) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateStatus() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateStatus()
	})
}

// SetDepartmentID sets the "department_id" field.
func (u *EnterpriseMemberUpsertBulk) SetDepartmentID(v int64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetDepartmentID(v)
	})
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateDepartmentID() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateDepartmentID()
	})
}

// ClearDepartmentID clears the value of the "department_id" field.
func (u *EnterpriseMemberUpsertBulk) ClearDepartmentID() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.ClearDepartmentID()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *EnterpriseMemberUpsertBulk) SetConcurrency(v int) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *EnterpriseMemberUpsertBulk) AddConcurrency(v int) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateConcurrency() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateConcurrency()
	})
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *EnterpriseMemberUpsertBulk) SetRpmLimit(v int) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRpmLimit(v)
	})
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *EnterpriseMemberUpsertBulk) AddRpmLimit(v int) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddRpmLimit(v)
	})
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateRpmLimit() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRpmLimit()
	})
}

// SetNotes sets the "notes" field.
func (u *EnterpriseMemberUpsertBulk) SetNotes(v string) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateNotes() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateNotes()
	})
}

// SetUnboundAt sets the "unbound_at" field.
func (u *EnterpriseMemberUpsertBulk) SetUnboundAt(v time.Time) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetUnboundAt(v)
	})
}

// UpdateUnboundAt sets the "unbound_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateUnboundAt() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateUnboundAt()
	})
}

// ClearUnboundAt clears the value of the "unbound_at" field.
func (u *EnterpriseMemberUpsertBulk) ClearUnboundAt() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.ClearUnboundAt()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
