// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/department"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EnterpriseMember is the model entity for the EnterpriseMember schema.
type EnterpriseMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 所属企业 ID
	EnterpriseID int64 `json:"enterprise_id,omitempty"`
	// 关联用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 企业内角色：enterprise_admin / enterprise_member
	Role string `json:"role,omitempty"`
	// active / unbound
	Status string `json:"status,omitempty"`
	// 所属部门 ID
	DepartmentID *int64 `json:"department_id,omitempty"`
	// 成员级并发上限，0=不限制
	Concurrency int `json:"concurrency,omitempty"`
	// 成员级 RPM 上限，0=不限制
	RpmLimit int `json:"rpm_limit,omitempty"`
	// 备注
	Notes string `json:"notes,omitempty"`
	// 加入企业时间
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// 解绑时间
	UnboundAt *time.Time `json:"unbound_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EnterpriseMemberQuery when eager-loading is set.
	Edges        EnterpriseMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EnterpriseMemberEdges holds the relations/edges for other nodes in the graph.
type EnterpriseMemberEdges struct {
	// Enterprise holds the value of the enterprise edge.
	Enterprise *Enterprise `json:"enterprise,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Department holds the value of the department edge.
	Department *Department `json:"department,omitempty"`
	// 分配给该成员的 API Key
	AssignedKeys []*APIKey `json:"assigned_keys,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// EnterpriseOrErr returns the Enterprise value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnterpriseMemberEdges) EnterpriseOrErr() (*Enterprise, error) {
	if e.Enterprise != nil {
		return e.Enterprise, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: enterprise.Label}
	}
	return nil, &NotLoadedError{edge: "enterprise"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnterpriseMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// DepartmentOrErr returns the Department value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnterpriseMemberEdges) DepartmentOrErr() (*Department, error) {
	if e.Department != nil {
		return e.Department, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: department.Label}
	}
	return nil, &NotLoadedError{edge: "department"}
}

// AssignedKeysOrErr returns the AssignedKeys value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseMemberEdges) AssignedKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[3] {
		return e.AssignedKeys, nil
	}
	return nil, &NotLoadedError{edge: "assigned_keys"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EnterpriseMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case enterprisemember.FieldID, enterprisemember.FieldEnterpriseID, enterprisemember.FieldUserID, enterprisemember.FieldDepartmentID, enterprisemember.FieldConcurrency, enterprisemember.FieldRpmLimit:
			values[i] = new(sql.NullInt64)
		case enterprisemember.FieldRole, enterprisemember.FieldStatus, enterprisemember.FieldNotes:
			values[i] = new(sql.NullString)
		case enterprisemember.FieldCreatedAt, enterprisemember.FieldUpdatedAt, enterprisemember.FieldDeletedAt, enterprisemember.FieldJoinedAt, enterprisemember.FieldUnboundAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EnterpriseMember fields.
func (_m *EnterpriseMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case enterprisemember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case enterprisemember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case enterprisemember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case enterprisemember.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case enterprisemember.FieldEnterpriseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enterprise_id", values[i])
			} else if value.Valid {
				_m.EnterpriseID = value.Int64
			}
		case enterprisemember.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case enterprisemember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case enterprisemember.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case enterprisemember.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = new(int64)
				*_m.DepartmentID = value.Int64
			}
		case enterprisemember.FieldConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency", values[i])
			} else if value.Valid {
				_m.Concurrency = int(value.Int64)
			}
		case enterprisemember.FieldRpmLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rpm_limit", values[i])
			} else if value.Valid {
				_m.RpmLimit = int(value.Int64)
			}
		case enterprisemember.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case enterprisemember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		case enterprisemember.FieldUnboundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field unbound_at", values[i])
			} else if value.Valid {
				_m.UnboundAt = new(time.Time)
				*_m.UnboundAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EnterpriseMember.
// This includes values selected through modifiers, order, etc.
func (_m *EnterpriseMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEnterprise queries the "enterprise" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryEnterprise() *EnterpriseQuery {
	return NewEnterpriseMemberClient(_m.config).QueryEnterprise(_m)
}

// QueryUser queries the "user" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryUser() *UserQuery {
	return NewEnterpriseMemberClient(_m.config).QueryUser(_m)
}

// QueryDepartment queries the "department" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryDepartment() *DepartmentQuery {
	return NewEnterpriseMemberClient(_m.config).QueryDepartment(_m)
}

// QueryAssignedKeys queries the "assigned_keys" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryAssignedKeys() *APIKeyQuery {
	return NewEnterpriseMemberClient(_m.config).QueryAssignedKeys(_m)
}

// Update returns a builder for updating this EnterpriseMember.
// Note that you need to call EnterpriseMember.Unwrap() before calling this method if this EnterpriseMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EnterpriseMember) Update() *EnterpriseMemberUpdateOne {
	return NewEnterpriseMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EnterpriseMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EnterpriseMember) Unwrap() *EnterpriseMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EnterpriseMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EnterpriseMember) String() string {
	var builder strings.Builder
	builder.WriteString("EnterpriseMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("enterprise_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnterpriseID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.DepartmentID; v != nil {
		builder.WriteString("department_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concurrency))
	builder.WriteString(", ")
	builder.WriteString("rpm_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.RpmLimit))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UnboundAt; v != nil {
		builder.WriteString("unbound_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// EnterpriseMembers is a parsable slice of EnterpriseMember.
type EnterpriseMembers []*EnterpriseMember
