// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/department"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisesubscription"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EnterpriseUpdate is the builder for updating Enterprise entities.
type EnterpriseUpdate struct {
	config
	hooks    []Hook
	mutation *EnterpriseMutation
}

// Where appends a list predicates to the EnterpriseUpdate builder.
func (_u *EnterpriseUpdate) Where(ps ...predicate.Enterprise) *EnterpriseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseUpdate) SetUpdatedAt(v time.Time) *EnterpriseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EnterpriseUpdate) SetDeletedAt(v time.Time) *EnterpriseUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableDeletedAt(v *time.Time) *EnterpriseUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EnterpriseUpdate) ClearDeletedAt() *EnterpriseUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *EnterpriseUpdate) SetName(v string) *EnterpriseUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableName(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetShortName sets the "short_name" field.
func (_u *EnterpriseUpdate) SetShortName(v string) *EnterpriseUpdate {
	_u.mutation.SetShortName(v)
	return _u
}

// SetNillableShortName sets the "short_name" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableShortName(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetShortName(*v)
	}
	return _u
}

// SetCreditCode sets the "credit_code" field.
func (_u *EnterpriseUpdate) SetCreditCode(v string) *EnterpriseUpdate {
	_u.mutation.SetCreditCode(v)
	return _u
}

// SetNillableCreditCode sets the "credit_code" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableCreditCode(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetCreditCode(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *EnterpriseUpdate) SetAddress(v string) *EnterpriseUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableAddress(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetScale sets the "scale" field.
func (_u *EnterpriseUpdate) SetScale(v string) *EnterpriseUpdate {
	_u.mutation.SetScale(v)
	return _u
}

// SetNillableScale sets the "scale" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableScale(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetScale(*v)
	}
	return _u
}

// SetIndustry sets the "industry" field.
func (_u *EnterpriseUpdate) SetIndustry(v string) *EnterpriseUpdate {
	_u.mutation.SetIndustry(v)
	return _u
}

// SetNillableIndustry sets the "industry" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableIndustry(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetIndustry(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *EnterpriseUpdate) SetParentID(v int64) *EnterpriseUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableParentID(v *int64) *EnterpriseUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *EnterpriseUpdate) AddParentID(v int64) *EnterpriseUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseUpdate) SetStatus(v string) *EnterpriseUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableStatus(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *EnterpriseUpdate) SetContactName(v string) *EnterpriseUpdate {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableContactName(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *EnterpriseUpdate) SetContactPhone(v string) *EnterpriseUpdate {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableContactPhone(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *EnterpriseUpdate) SetContactEmail(v string) *EnterpriseUpdate {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableContactEmail(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EnterpriseUpdate) SetNotes(v string) *EnterpriseUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableNotes(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *EnterpriseUpdate) SetBalance(v float64) *EnterpriseUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableBalance(v *float64) *EnterpriseUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *EnterpriseUpdate) AddBalance(v float64) *EnterpriseUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetTotalRecharged sets the "total_recharged" field.
func (_u *EnterpriseUpdate) SetTotalRecharged(v float64) *EnterpriseUpdate {
	_u.mutation.ResetTotalRecharged()
	_u.mutation.SetTotalRecharged(v)
	return _u
}

// SetNillableTotalRecharged sets the "total_recharged" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableTotalRecharged(v *float64) *EnterpriseUpdate {
	if v != nil {
		_u.SetTotalRecharged(*v)
	}
	return _u
}

// AddTotalRecharged adds value to the "total_recharged" field.
func (_u *EnterpriseUpdate) AddTotalRecharged(v float64) *EnterpriseUpdate {
	_u.mutation.AddTotalRecharged(v)
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *EnterpriseUpdate) SetConcurrency(v int) *EnterpriseUpdate {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableConcurrency(v *int) *EnterpriseUpdate {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *EnterpriseUpdate) AddConcurrency(v int) *EnterpriseUpdate {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetAdminUserID sets the "admin_user_id" field.
func (_u *EnterpriseUpdate) SetAdminUserID(v int64) *EnterpriseUpdate {
	_u.mutation.SetAdminUserID(v)
	return _u
}

// SetNillableAdminUserID sets the "admin_user_id" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableAdminUserID(v *int64) *EnterpriseUpdate {
	if v != nil {
		_u.SetAdminUserID(*v)
	}
	return _u
}

// SetAdminID sets the "admin" edge to the User entity by ID.
func (_u *EnterpriseUpdate) SetAdminID(id int64) *EnterpriseUpdate {
	_u.mutation.SetAdminID(id)
	return _u
}

// SetAdmin sets the "admin" edge to the User entity.
func (_u *EnterpriseUpdate) SetAdmin(v *User) *EnterpriseUpdate {
	return _u.SetAdminID(v.ID)
}

// AddMemberIDs adds the "members" edge to the EnterpriseMember entity by IDs.
func (_u *EnterpriseUpdate) AddMemberIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the EnterpriseMember entity.
func (_u *EnterpriseUpdate) AddMembers(v ...*EnterpriseMember) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddDepartmentIDs adds the "departments" edge to the Department entity by IDs.
func (_u *EnterpriseUpdate) AddDepartmentIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.AddDepartmentIDs(ids...)
	return _u
}

// AddDepartments adds the "departments" edges to the Department entity.
func (_u *EnterpriseUpdate) AddDepartments(v ...*Department) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDepartmentIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the EnterpriseSubscription entity by IDs.
func (_u *EnterpriseUpdate) AddSubscriptionIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the EnterpriseSubscription entity.
func (_u *EnterpriseUpdate) AddSubscriptions(v ...*EnterpriseSubscription) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *EnterpriseUpdate) AddUsageLogIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *EnterpriseUpdate) AddUsageLogs(v ...*UsageLog) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the EnterpriseMutation object of the builder.
func (_u *EnterpriseUpdate) Mutation() *EnterpriseMutation {
	return _u.mutation
}

// ClearAdmin clears the "admin" edge to the User entity.
func (_u *EnterpriseUpdate) ClearAdmin() *EnterpriseUpdate {
	_u.mutation.ClearAdmin()
	return _u
}

// ClearMembers clears all "members" edges to the EnterpriseMember entity.
func (_u *EnterpriseUpdate) ClearMembers() *EnterpriseUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to EnterpriseMember entities by IDs.
func (_u *EnterpriseUpdate) RemoveMemberIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to EnterpriseMember entities.
func (_u *EnterpriseUpdate) RemoveMembers(v ...*EnterpriseMember) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearDepartments clears all "departments" edges to the Department entity.
func (_u *EnterpriseUpdate) ClearDepartments() *EnterpriseUpdate {
	_u.mutation.ClearDepartments()
	return _u
}

// RemoveDepartmentIDs removes the "departments" edge to Department entities by IDs.
func (_u *EnterpriseUpdate) RemoveDepartmentIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.RemoveDepartmentIDs(ids...)
	return _u
}

// RemoveDepartments removes "departments" edges to Department entities.
func (_u *EnterpriseUpdate) RemoveDepartments(v ...*Department) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDepartmentIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the EnterpriseSubscription entity.
func (_u *EnterpriseUpdate) ClearSubscriptions() *EnterpriseUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to EnterpriseSubscription entities by IDs.
func (_u *EnterpriseUpdate) RemoveSubscriptionIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to EnterpriseSubscription entities.
func (_u *EnterpriseUpdate) RemoveSubscriptions(v ...*EnterpriseSubscription) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *EnterpriseUpdate) ClearUsageLogs() *EnterpriseUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *EnterpriseUpdate) RemoveUsageLogIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *EnterpriseUpdate) RemoveUsageLogs(v ...*UsageLog) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnterpriseUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnterpriseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if enterprise.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprise.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprise.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := enterprise.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ShortName(); ok {
		if err := enterprise.ShortNameValidator(v); err != nil {
			return &ValidationError{Name: "short_name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.short_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreditCode(); ok {
		if err := enterprise.CreditCodeValidator(v); err != nil {
			return &ValidationError{Name: "credit_code", err: fmt.Errorf(`ent: validator failed for field "Enterprise.credit_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := enterprise.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Enterprise.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scale(); ok {
		if err := enterprise.ScaleValidator(v); err != nil {
			return &ValidationError{Name: "scale", err: fmt.Errorf(`ent: validator failed for field "Enterprise.scale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Industry(); ok {
		if err := enterprise.IndustryValidator(v); err != nil {
			return &ValidationError{Name: "industry", err: fmt.Errorf(`ent: validator failed for field "Enterprise.industry": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprise.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Enterprise.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactName(); ok {
		if err := enterprise.ContactNameValidator(v); err != nil {
			return &ValidationError{Name: "contact_name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.contact_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactPhone(); ok {
		if err := enterprise.ContactPhoneValidator(v); err != nil {
			return &ValidationError{Name: "contact_phone", err: fmt.Errorf(`ent: validator failed for field "Enterprise.contact_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactEmail(); ok {
		if err := enterprise.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "Enterprise.contact_email": %w`, err)}
		}
	}
	if _u.mutation.AdminCleared() && len(_u.mutation.AdminIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Enterprise.admin"`)
	}
	return nil
}

func (_u *EnterpriseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprise.Table, enterprise.Columns, sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprise.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(enterprise.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(enterprise.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(enterprise.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShortName(); ok {
		_spec.SetField(enterprise.FieldShortName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditCode(); ok {
		_spec.SetField(enterprise.FieldCreditCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(enterprise.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scale(); ok {
		_spec.SetField(enterprise.FieldScale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Industry(); ok {
		_spec.SetField(enterprise.FieldIndustry, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(enterprise.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(enterprise.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprise.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(enterprise.FieldContactName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(enterprise.FieldContactPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(enterprise.FieldContactEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(enterprise.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(enterprise.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(enterprise.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRecharged(); ok {
		_spec.SetField(enterprise.FieldTotalRecharged, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalRecharged(); ok {
		_spec.AddField(enterprise.FieldTotalRecharged, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(enterprise.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(enterprise.FieldConcurrency, field.TypeInt, value)
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprise.AdminTable,
			Columns: []string{enterprise.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprise.AdminTable,
			Columns: []string{enterprise.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.MembersTable,
			Columns: []string{enterprise.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.MembersTable,
			Columns: []string{enterprise.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.MembersTable,
			Columns: []string{enterprise.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.DepartmentsTable,
			Columns: []string{enterprise.DepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDepartmentsIDs(); len(nodes) > 0 && !_u.mutation.DepartmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.DepartmentsTable,
			Columns: []string{enterprise.DepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.DepartmentsTable,
			Columns: []string{enterprise.DepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.SubscriptionsTable,
			Columns: []string{enterprise.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.SubscriptionsTable,
			Columns: []string{enterprise.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.SubscriptionsTable,
			Columns: []string{enterprise.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.UsageLogsTable,
			Columns: []string{enterprise.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.UsageLogsTable,
			Columns: []string{enterprise.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.UsageLogsTable,
			Columns: []string{enterprise.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprise.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnterpriseUpdateOne is the builder for updating a single Enterprise entity.
type EnterpriseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnterpriseMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseUpdateOne) SetUpdatedAt(v time.Time) *EnterpriseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EnterpriseUpdateOne) SetDeletedAt(v time.Time) *EnterpriseUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableDeletedAt(v *time.Time) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EnterpriseUpdateOne) ClearDeletedAt() *EnterpriseUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *EnterpriseUpdateOne) SetName(v string) *EnterpriseUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableName(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetShortName sets the "short_name" field.
func (_u *EnterpriseUpdateOne) SetShortName(v string) *EnterpriseUpdateOne {
	_u.mutation.SetShortName(v)
	return _u
}

// SetNillableShortName sets the "short_name" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableShortName(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetShortName(*v)
	}
	return _u
}

// SetCreditCode sets the "credit_code" field.
func (_u *EnterpriseUpdateOne) SetCreditCode(v string) *EnterpriseUpdateOne {
	_u.mutation.SetCreditCode(v)
	return _u
}

// SetNillableCreditCode sets the "credit_code" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableCreditCode(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetCreditCode(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *EnterpriseUpdateOne) SetAddress(v string) *EnterpriseUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableAddress(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetScale sets the "scale" field.
func (_u *EnterpriseUpdateOne) SetScale(v string) *EnterpriseUpdateOne {
	_u.mutation.SetScale(v)
	return _u
}

// SetNillableScale sets the "scale" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableScale(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetScale(*v)
	}
	return _u
}

// SetIndustry sets the "industry" field.
func (_u *EnterpriseUpdateOne) SetIndustry(v string) *EnterpriseUpdateOne {
	_u.mutation.SetIndustry(v)
	return _u
}

// SetNillableIndustry sets the "industry" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableIndustry(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetIndustry(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *EnterpriseUpdateOne) SetParentID(v int64) *EnterpriseUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableParentID(v *int64) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *EnterpriseUpdateOne) AddParentID(v int64) *EnterpriseUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseUpdateOne) SetStatus(v string) *EnterpriseUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableStatus(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *EnterpriseUpdateOne) SetContactName(v string) *EnterpriseUpdateOne {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableContactName(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *EnterpriseUpdateOne) SetContactPhone(v string) *EnterpriseUpdateOne {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableContactPhone(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *EnterpriseUpdateOne) SetContactEmail(v string) *EnterpriseUpdateOne {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableContactEmail(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EnterpriseUpdateOne) SetNotes(v string) *EnterpriseUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableNotes(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *EnterpriseUpdateOne) SetBalance(v float64) *EnterpriseUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableBalance(v *float64) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *EnterpriseUpdateOne) AddBalance(v float64) *EnterpriseUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetTotalRecharged sets the "total_recharged" field.
func (_u *EnterpriseUpdateOne) SetTotalRecharged(v float64) *EnterpriseUpdateOne {
	_u.mutation.ResetTotalRecharged()
	_u.mutation.SetTotalRecharged(v)
	return _u
}

// SetNillableTotalRecharged sets the "total_recharged" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableTotalRecharged(v *float64) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetTotalRecharged(*v)
	}
	return _u
}

// AddTotalRecharged adds value to the "total_recharged" field.
func (_u *EnterpriseUpdateOne) AddTotalRecharged(v float64) *EnterpriseUpdateOne {
	_u.mutation.AddTotalRecharged(v)
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *EnterpriseUpdateOne) SetConcurrency(v int) *EnterpriseUpdateOne {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableConcurrency(v *int) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *EnterpriseUpdateOne) AddConcurrency(v int) *EnterpriseUpdateOne {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetAdminUserID sets the "admin_user_id" field.
func (_u *EnterpriseUpdateOne) SetAdminUserID(v int64) *EnterpriseUpdateOne {
	_u.mutation.SetAdminUserID(v)
	return _u
}

// SetNillableAdminUserID sets the "admin_user_id" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableAdminUserID(v *int64) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetAdminUserID(*v)
	}
	return _u
}

// SetAdminID sets the "admin" edge to the User entity by ID.
func (_u *EnterpriseUpdateOne) SetAdminID(id int64) *EnterpriseUpdateOne {
	_u.mutation.SetAdminID(id)
	return _u
}

// SetAdmin sets the "admin" edge to the User entity.
func (_u *EnterpriseUpdateOne) SetAdmin(v *User) *EnterpriseUpdateOne {
	return _u.SetAdminID(v.ID)
}

// AddMemberIDs adds the "members" edge to the EnterpriseMember entity by IDs.
func (_u *EnterpriseUpdateOne) AddMemberIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the EnterpriseMember entity.
func (_u *EnterpriseUpdateOne) AddMembers(v ...*EnterpriseMember) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddDepartmentIDs adds the "departments" edge to the Department entity by IDs.
func (_u *EnterpriseUpdateOne) AddDepartmentIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.AddDepartmentIDs(ids...)
	return _u
}

// AddDepartments adds the "departments" edges to the Department entity.
func (_u *EnterpriseUpdateOne) AddDepartments(v ...*Department) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDepartmentIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the EnterpriseSubscription entity by IDs.
func (_u *EnterpriseUpdateOne) AddSubscriptionIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the EnterpriseSubscription entity.
func (_u *EnterpriseUpdateOne) AddSubscriptions(v ...*EnterpriseSubscription) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *EnterpriseUpdateOne) AddUsageLogIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *EnterpriseUpdateOne) AddUsageLogs(v ...*UsageLog) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the EnterpriseMutation object of the builder.
func (_u *EnterpriseUpdateOne) Mutation() *EnterpriseMutation {
	return _u.mutation
}

// ClearAdmin clears the "admin" edge to the User entity.
func (_u *EnterpriseUpdateOne) ClearAdmin() *EnterpriseUpdateOne {
	_u.mutation.ClearAdmin()
	return _u
}

// ClearMembers clears all "members" edges to the EnterpriseMember entity.
func (_u *EnterpriseUpdateOne) ClearMembers() *EnterpriseUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to EnterpriseMember entities by IDs.
func (_u *EnterpriseUpdateOne) RemoveMemberIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to EnterpriseMember entities.
func (_u *EnterpriseUpdateOne) RemoveMembers(v ...*EnterpriseMember) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearDepartments clears all "departments" edges to the Department entity.
func (_u *EnterpriseUpdateOne) ClearDepartments() *EnterpriseUpdateOne {
	_u.mutation.ClearDepartments()
	return _u
}

// RemoveDepartmentIDs removes the "departments" edge to Department entities by IDs.
func (_u *EnterpriseUpdateOne) RemoveDepartmentIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.RemoveDepartmentIDs(ids...)
	return _u
}

// RemoveDepartments removes "departments" edges to Department entities.
func (_u *EnterpriseUpdateOne) RemoveDepartments(v ...*Department) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDepartmentIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the EnterpriseSubscription entity.
func (_u *EnterpriseUpdateOne) ClearSubscriptions() *EnterpriseUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to EnterpriseSubscription entities by IDs.
func (_u *EnterpriseUpdateOne) RemoveSubscriptionIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to EnterpriseSubscription entities.
func (_u *EnterpriseUpdateOne) RemoveSubscriptions(v ...*EnterpriseSubscription) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *EnterpriseUpdateOne) ClearUsageLogs() *EnterpriseUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *EnterpriseUpdateOne) RemoveUsageLogIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *EnterpriseUpdateOne) RemoveUsageLogs(v ...*UsageLog) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the EnterpriseUpdate builder.
func (_u *EnterpriseUpdateOne) Where(ps ...predicate.Enterprise) *EnterpriseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnterpriseUpdateOne) Select(field string, fields ...string) *EnterpriseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Enterprise entity.
func (_u *EnterpriseUpdateOne) Save(ctx context.Context) (*Enterprise, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseUpdateOne) SaveX(ctx context.Context) *Enterprise {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnterpriseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if enterprise.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprise.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprise.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := enterprise.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ShortName(); ok {
		if err := enterprise.ShortNameValidator(v); err != nil {
			return &ValidationError{Name: "short_name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.short_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreditCode(); ok {
		if err := enterprise.CreditCodeValidator(v); err != nil {
			return &ValidationError{Name: "credit_code", err: fmt.Errorf(`ent: validator failed for field "Enterprise.credit_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := enterprise.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Enterprise.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scale(); ok {
		if err := enterprise.ScaleValidator(v); err != nil {
			return &ValidationError{Name: "scale", err: fmt.Errorf(`ent: validator failed for field "Enterprise.scale": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Industry(); ok {
		if err := enterprise.IndustryValidator(v); err != nil {
			return &ValidationError{Name: "industry", err: fmt.Errorf(`ent: validator failed for field "Enterprise.industry": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprise.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Enterprise.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactName(); ok {
		if err := enterprise.ContactNameValidator(v); err != nil {
			return &ValidationError{Name: "contact_name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.contact_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactPhone(); ok {
		if err := enterprise.ContactPhoneValidator(v); err != nil {
			return &ValidationError{Name: "contact_phone", err: fmt.Errorf(`ent: validator failed for field "Enterprise.contact_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactEmail(); ok {
		if err := enterprise.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "Enterprise.contact_email": %w`, err)}
		}
	}
	if _u.mutation.AdminCleared() && len(_u.mutation.AdminIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Enterprise.admin"`)
	}
	return nil
}

func (_u *EnterpriseUpdateOne) sqlSave(ctx context.Context) (_node *Enterprise, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprise.Table, enterprise.Columns, sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Enterprise.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enterprise.FieldID)
		for _, f := range fields {
			if !enterprise.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enterprise.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprise.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(enterprise.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(enterprise.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(enterprise.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShortName(); ok {
		_spec.SetField(enterprise.FieldShortName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditCode(); ok {
		_spec.SetField(enterprise.FieldCreditCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(enterprise.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scale(); ok {
		_spec.SetField(enterprise.FieldScale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Industry(); ok {
		_spec.SetField(enterprise.FieldIndustry, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(enterprise.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(enterprise.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprise.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(enterprise.FieldContactName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(enterprise.FieldContactPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(enterprise.FieldContactEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(enterprise.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(enterprise.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(enterprise.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRecharged(); ok {
		_spec.SetField(enterprise.FieldTotalRecharged, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalRecharged(); ok {
		_spec.AddField(enterprise.FieldTotalRecharged, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(enterprise.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(enterprise.FieldConcurrency, field.TypeInt, value)
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprise.AdminTable,
			Columns: []string{enterprise.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprise.AdminTable,
			Columns: []string{enterprise.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.MembersTable,
			Columns: []string{enterprise.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.MembersTable,
			Columns: []string{enterprise.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.MembersTable,
			Columns: []string{enterprise.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.DepartmentsTable,
			Columns: []string{enterprise.DepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDepartmentsIDs(); len(nodes) > 0 && !_u.mutation.DepartmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.DepartmentsTable,
			Columns: []string{enterprise.DepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.DepartmentsTable,
			Columns: []string{enterprise.DepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.SubscriptionsTable,
			Columns: []string{enterprise.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.SubscriptionsTable,
			Columns: []string{enterprise.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.SubscriptionsTable,
			Columns: []string{enterprise.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisesubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.UsageLogsTable,
			Columns: []string{enterprise.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.UsageLogsTable,
			Columns: []string{enterprise.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprise.UsageLogsTable,
			Columns: []string{enterprise.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Enterprise{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprise.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
