// Code generated by ent, DO NOT EDIT.

package enterprisemember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldDeletedAt, v))
}

// EnterpriseID applies equality check predicate on the "enterprise_id" field. It's identical to EnterpriseIDEQ.
func EnterpriseID(v int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldEnterpriseID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldUserID, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldRole, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldStatus, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldDepartmentID, v))
}

// Concurrency applies equality check predicate on the "concurrency" field. It's identical to ConcurrencyEQ.
func Concurrency(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldConcurrency, v))
}

// RpmLimit applies equality check predicate on the "rpm_limit" field. It's identical to RpmLimitEQ.
func RpmLimit(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldRpmLimit, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldNotes, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldJoinedAt, v))
}

// UnboundAt applies equality check predicate on the "unbound_at" field. It's identical to UnboundAtEQ.
func UnboundAt(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldUnboundAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotNull(FieldDeletedAt))
}

// EnterpriseIDEQ applies the EQ predicate on the "enterprise_id" field.
func EnterpriseIDEQ(v int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldEnterpriseID, v))
}

// EnterpriseIDNEQ applies the NEQ predicate on the "enterprise_id" field.
func EnterpriseIDNEQ(v int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldEnterpriseID, v))
}

// EnterpriseIDIn applies the In predicate on the "enterprise_id" field.
func EnterpriseIDIn(vs ...int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldEnterpriseID, vs...))
}

// EnterpriseIDNotIn applies the NotIn predicate on the "enterprise_id" field.
func EnterpriseIDNotIn(vs ...int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldEnterpriseID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldUserID, vs...))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldContainsFold(FieldRole, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldContainsFold(FieldStatus, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...int64) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDIsNil applies the IsNil predicate on the "department_id" field.
func DepartmentIDIsNil() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIsNull(FieldDepartmentID))
}

// DepartmentIDNotNil applies the NotNil predicate on the "department_id" field.
func DepartmentIDNotNil() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotNull(FieldDepartmentID))
}

// ConcurrencyEQ applies the EQ predicate on the "concurrency" field.
func ConcurrencyEQ(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldConcurrency, v))
}

// ConcurrencyNEQ applies the NEQ predicate on the "concurrency" field.
func ConcurrencyNEQ(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldConcurrency, v))
}

// ConcurrencyIn applies the In predicate on the "concurrency" field.
func ConcurrencyIn(vs ...int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldConcurrency, vs...))
}

// ConcurrencyNotIn applies the NotIn predicate on the "concurrency" field.
func ConcurrencyNotIn(vs ...int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldConcurrency, vs...))
}

// ConcurrencyGT applies the GT predicate on the "concurrency" field.
func ConcurrencyGT(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldConcurrency, v))
}

// ConcurrencyGTE applies the GTE predicate on the "concurrency" field.
func ConcurrencyGTE(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldConcurrency, v))
}

// ConcurrencyLT applies the LT predicate on the "concurrency" field.
func ConcurrencyLT(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldConcurrency, v))
}

// ConcurrencyLTE applies the LTE predicate on the "concurrency" field.
func ConcurrencyLTE(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldConcurrency, v))
}

// RpmLimitEQ applies the EQ predicate on the "rpm_limit" field.
func RpmLimitEQ(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldRpmLimit, v))
}

// RpmLimitNEQ applies the NEQ predicate on the "rpm_limit" field.
func RpmLimitNEQ(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldRpmLimit, v))
}

// RpmLimitIn applies the In predicate on the "rpm_limit" field.
func RpmLimitIn(vs ...int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldRpmLimit, vs...))
}

// RpmLimitNotIn applies the NotIn predicate on the "rpm_limit" field.
func RpmLimitNotIn(vs ...int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldRpmLimit, vs...))
}

// RpmLimitGT applies the GT predicate on the "rpm_limit" field.
func RpmLimitGT(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldRpmLimit, v))
}

// RpmLimitGTE applies the GTE predicate on the "rpm_limit" field.
func RpmLimitGTE(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldRpmLimit, v))
}

// RpmLimitLT applies the LT predicate on the "rpm_limit" field.
func RpmLimitLT(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldRpmLimit, v))
}

// RpmLimitLTE applies the LTE predicate on the "rpm_limit" field.
func RpmLimitLTE(v int) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldRpmLimit, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldContainsFold(FieldNotes, v))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldJoinedAt, v))
}

// UnboundAtEQ applies the EQ predicate on the "unbound_at" field.
func UnboundAtEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldEQ(FieldUnboundAt, v))
}

// UnboundAtNEQ applies the NEQ predicate on the "unbound_at" field.
func UnboundAtNEQ(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNEQ(FieldUnboundAt, v))
}

// UnboundAtIn applies the In predicate on the "unbound_at" field.
func UnboundAtIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIn(FieldUnboundAt, vs...))
}

// UnboundAtNotIn applies the NotIn predicate on the "unbound_at" field.
func UnboundAtNotIn(vs ...time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotIn(FieldUnboundAt, vs...))
}

// UnboundAtGT applies the GT predicate on the "unbound_at" field.
func UnboundAtGT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGT(FieldUnboundAt, v))
}

// UnboundAtGTE applies the GTE predicate on the "unbound_at" field.
func UnboundAtGTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldGTE(FieldUnboundAt, v))
}

// UnboundAtLT applies the LT predicate on the "unbound_at" field.
func UnboundAtLT(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLT(FieldUnboundAt, v))
}

// UnboundAtLTE applies the LTE predicate on the "unbound_at" field.
func UnboundAtLTE(v time.Time) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldLTE(FieldUnboundAt, v))
}

// UnboundAtIsNil applies the IsNil predicate on the "unbound_at" field.
func UnboundAtIsNil() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldIsNull(FieldUnboundAt))
}

// UnboundAtNotNil applies the NotNil predicate on the "unbound_at" field.
func UnboundAtNotNil() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.FieldNotNull(FieldUnboundAt))
}

// HasEnterprise applies the HasEdge predicate on the "enterprise" edge.
func HasEnterprise() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EnterpriseTable, EnterpriseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnterpriseWith applies the HasEdge predicate on the "enterprise" edge with a given conditions (other predicates).
func HasEnterpriseWith(preds ...predicate.Enterprise) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(func(s *sql.Selector) {
		step := newEnterpriseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartment applies the HasEdge predicate on the "department" edge.
func HasDepartment() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentWith applies the HasEdge predicate on the "department" edge with a given conditions (other predicates).
func HasDepartmentWith(preds ...predicate.Department) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(func(s *sql.Selector) {
		step := newDepartmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedKeys applies the HasEdge predicate on the "assigned_keys" edge.
func HasAssignedKeys() predicate.EnterpriseMember {
	return predicate.EnterpriseMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssignedKeysTable, AssignedKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedKeysWith applies the HasEdge predicate on the "assigned_keys" edge with a given conditions (other predicates).
func HasAssignedKeysWith(preds ...predicate.APIKey) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(func(s *sql.Selector) {
		step := newAssignedKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EnterpriseMember) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EnterpriseMember) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EnterpriseMember) predicate.EnterpriseMember {
	return predicate.EnterpriseMember(sql.NotPredicates(p))
}
